# -*- mode: org -*-
#+TITLE: Contrôler un environnement logiciel avec Guix
#+DATE: Septembre 2020
#+STARTUP: overview indent
#+OPTIONS: num:nil toc:t
#+PROPERTY: header-args :eval never-export

* Plan
- Point de départ
- Séquence 2 : Créer son propre environnement, automatiser sa construction et le partage
 - 2.2 Installer tous les paquets dont on a besoin
 - 2.4 Automatiser la construction de son environnement
 - 2.5 Mieux connaître son environnement
 - 2.6 Mettre son environnement à disposition
 - 2.7 Reconstruire un environnement
 - 2.8 Mettre son environnement à disposition sous forme d'une image Docker
 - 2.9 Modifier son environnement

* Point de départ
Pour utiliser Guix, il faut évidemment l'installer. Il y a deux façons d'y arriver :

1. Installer [[https://guix.gnu.org/manual/en/html_node/System-Installation.html][Guix System]] sur votre ordinateur, à la place d'une distribution Linux plus traditionnelle comme Debian ou Ubuntu. Tout votre système est alors géré avec Guix, ce qui a des avantages (notamment la reproductibilité totale de votre configuration), mais aussi des inconvénients (il y a moins de logiciels disponibles pour Guix que pour une vieille distribution genre Debian). Vous pouvez bien sûr installer Guix dans une machine virtuelle.

2. Installer seulement [[https://guix.gnu.org/manual/en/html_node/Binary-Installation.html][le gestionnaire de paquets Guix]] sur un ordinateur qui tourne déjà sous Linux. Vous pouvez alors utiliser Guix en parallèle avec le gestionnaire de paquets de votre distribution, ce qui donne beaucoup de flexibilité, mais il faut bien sûr faire attention à quel paquet est installé comment, et éviter des doublons. Python est particulièrement problématique, parce que la coexistence de plusieurs installations de Python nécessite quelques précautions (qui n'ont rien à voir avec Guix d'ailleurs). Votre distribution Linux a fort probablement déjà une installation Python, et ce tutoriel vous fera travailler avec un Python fourni par Guix, ce qui crée la possibilité d'un conflit. Si vous rencontrez des difficultés que vous ne pouvez pas résoudre (normalement le résultat d'une configuration personnalisée par $PATH et/ou $PYTHONPATH), persévérez : dès que vous arrivez au point où je commence à utiliser "guix environment", ça devrait fonctionner quand-même (c'est fait pour !).

D'abord, quelques mots sur le fonctionnement de Guix pour les habitués de Linux - si vous ne comprenez pas ces explications, ce n'est pas grave pour la suite. La gestion traditionnelle des logiciels sous Linux est basée sur des conventions définissant l'emplacement des fichiers. Par exemple, les exécutables se trouvent sous =/bin=, =/usr/bin=, et =/usr/local/bin=. Ce genre de conventions sont très contraignantes parce qu'elles vous empêchent d'installer facilement plusieurs versions d'un même logiciel.

Guix fonctionne autrement : il place tous les fichiers sous =/gnu/store=, où chaque paquet à son sous-répertoire avec un nom très long et très bizarre comme par exemple =/gnu/store/kwf1gzgk7f0l1sz84d0frrfvlqysnbz7-jupyter-1.0.0=. Les 32 premiers caractères de ces noms de ces sous-répertoires sont en fait une somme de contrôle calculée sur le code source du logiciel et de toutes ses dépendances. Si vous installez Jupyter 1.0.0 avec une autre version de Python, cette somme de contrôle change, et elle change même si vous compilez Python avec une autre version de =gcc=. C'est comme ça que Guix permet la coexistence de plusieurs versions.

Sur cette base, Guix introduit des /profils/, qui remplacent la collection conventionnelle des répertoires comme =/bin=, =/lib=, =/etc=, etc. À l'intérieur d'un profil, vous retrouvez ces répertoires, mais leur contenu ne consiste que de liens symboliques vers les paquets sous =/gnu/store=. Chaque utilisateur a son profil personnel, sous =$HOME/.guix-profile=. C'est comme ça que chaque utilisateur peut gérer sa propre collection de logiciels, sans dépendre d'un administrateur pour les installer ou mettre à jour. Et comme les profils sont légers, on peut en définir d'autres à volonté (mais je n'en parle pas dans ce tutoriel). On peut aussi travailler avec des profils éphémères qui s'appellent "environnements". C'est cette approche que j'ai choisi pour ce tutoriel.

* Séquence 2 : Créer son propre environnement, automatiser sa construction et le partage

** Préparation
Avant de lancer =org-babel-tangle=, il faut créer tous les répertoires qui vont accueillir les fichiers, après en avoir supprimé des versions anciennes :
#+begin_src sh :results output :exports both
directory=moocrr_guix_jupyter
rm -rf $directory
mkdir $directory
#+end_src

#+RESULTS:

Puis :
#+begin_src emacs-lisp
(org-babel-tangle)
#+end_src

#+RESULTS:
| moocrr_guix_jupyter/manifest-with-pandas-1.0.4.scm | moocrr_guix_jupyter/pandas.scm | moocrr_guix_jupyter/all-dependencies.scm | moocrr_guix_jupyter/installed-dependencies.scm | moocrr_guix_jupyter/manifest.scm |

** 2.2 Installer tous les paquets dont on a besoin
Une installation Guix de base ne contient même pas Python,
il va donc falloir l'installer ainsi que Jupyter et différents paquets
comme =matplotlib=, =pandas=, =numpy=, =statsmodels=... L'installation
se fait à l'aide de la commande =guix install <nom_du_paquet>=. Comment
faire pour trouver le nom du paquet Guix qui contient ce qui vous intéresse ?
Avec la commande =guix search <un truc lié au nom de ce que vous cherchez>=.

D'abord, je cherche tout ce qui a trait à Jupyter :
#+begin_src sh :results output :exports both 
guix search jupyter
#+end_src

#+RESULTS:
#+begin_example
name: jupyter
version: 1.0.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipykernel@5.1.3 python-ipywidgets@7.5.1
+ python-jupyter-console@6.1.0 python-nbconvert@5.0.0b1 python-notebook@5.7.4
+ python-qtconsole@4.4.3
location: gnu/packages/python-xyz.scm:9946:2
homepage: https://jupyter.org
license: Modified BSD
synopsis: Web application for interactive documents  
description: The Jupyter Notebook is a web application that allows you to
+ create and share documents that contain live code, equations, visualizations
+ and explanatory text.  Uses include: data cleaning and transformation,
+ numerical simulation, statistical modeling, machine learning and much more.
relevance: 22

name: python-jupyter-kernel-test
version: 0.3
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-jsonschema@3.2.0 python-jupyter-kernel-mgmt@0.4.0
+ python-jupyter-protocol@0.1.1
location: gnu/packages/jupyter.scm:98:2
homepage: https://github.com/jupyter/jupyter_kernel_test
license: Modified BSD
synopsis: Test Jupyter kernels  
description: `jupyter_kernel_test' is a tool for testing Jupyter kernels.  It
+ tests kernels for successful code execution and conformance with the Jupyter
+ Messaging Protocol
+ (https://jupyter-client.readthedocs.io/en/latest/messaging.html).
relevance: 20

name: xeus
version: 0.23.2
outputs: out
systems: x86_64-linux i686-linux
dependencies: cppzmq@4.6.0 googletest@1.10.0 json-modern-cxx@3.9.1
+ openssl@1.1.1f pkg-config@0.29.2 python-jupyter-client@5.2.4
+ python-jupyter-kernel-test@0.3 python-pytest@5.3.5 python@3.8.2
+ util-linux@2.35.1 xtl@0.6.18 zeromq@4.3.2
location: gnu/packages/jupyter.scm:142:2
homepage: https://quantstack.net/xeus
license: Modified BSD
synopsis: C++ implementation of the Jupyter Kernel protocol  
description: `xeus' is a library meant to facilitate the implementation of
+ kernels for Jupyter.  It takes the burden of implementing the Jupyter Kernel
+ protocol so developers can focus on implementing the interpreter part of the
+ kernel.
+ 
+ Several Jupyter kernels are built upon `xeus', such as `xeus-cling', a kernel
+ for the C++ programming language, and `xeus-python', an alternative Python
+ kernel for Jupyter.
relevance: 16

name: python-jupyter-protocol
version: 0.1.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-dateutil@2.8.1 python-ipykernel@5.1.3
+ python-ipython@7.9.0 python-jupyter-core@4.4.0 python-mock@3.0.5
+ python-pytest@5.3.5 python-pyzmq@17.1.2 python-traitlets@4.3.3
location: gnu/packages/jupyter.scm:37:2
homepage: https://jupyter.org
license: Modified BSD
synopsis: Jupyter protocol implementation  
description: This Python library is an experimental implementation of the
+ Jupyter protocol
+ (https://jupyter-client.readthedocs.io/en/latest/messaging.html) to be used by
+ both clients and kernels.
relevance: 16

name: python2-jupyter-client
version: 5.2.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: iproute2@5.8.0 python2-jupyter-core@4.4.0 python2-pyzmq@17.1.2
+ python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6612:2
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Jupyter protocol implementation and client libraries  
description: The `jupyter_client' package contains the reference
+ implementation of the Jupyter protocol.  It also provides client and kernel
+ management APIs for working with kernels, and the `jupyter kernelspec'
+ entrypoint for installing `kernelspec's for use with Jupyter frontends.
relevance: 15

name: python-jupyter-client
version: 5.2.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: iproute2@5.8.0 python-jupyter-core@4.4.0 python-pyzmq@17.1.2
+ python-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6612:2
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Jupyter protocol implementation and client libraries  
description: The `jupyter_client' package contains the reference
+ implementation of the Jupyter protocol.  It also provides client and kernel
+ management APIs for working with kernels, and the `jupyter kernelspec'
+ entrypoint for installing `kernelspec's for use with Jupyter frontends.
relevance: 15

name: python-jupyter-kernel-mgmt
version: 0.4.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-dateutil@2.8.1 python-entrypoints@0.3
+ python-ipykernel@5.1.3 python-ipython@7.9.0 python-jupyter-core@4.4.0
+ python-jupyter-protocol@0.1.1 python-mock@3.0.5 python-pytest@5.3.5
+ python-pyzmq@17.1.2 python-traitlets@4.3.3
location: gnu/packages/jupyter.scm:67:2
homepage: https://jupyter.org
license: Modified BSD
synopsis: Discover, launch, and communicate with Jupyter kernels  
description: This package is an experimental refactoring of the machinery for
+ launching and using Jupyter kernels.
relevance: 14

name: guix-jupyter
version: 0.1.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: autoconf@2.69 automake@1.16.2 guile-gcrypt@0.3.0
+ guile-json@4.3.2 guile-simple-zmq@0.0.0-3.68bedb6 guile@3.0.4
+ guix@1.1.0-25.44c6e6f jupyter@1.0.0 pkg-config@0.29.2 python-ipykernel@5.1.3
+ python-ipython@7.9.0
location: gnu/packages/package-management.scm:985:2
homepage: https://gitlab.inria.fr/guix-hpc/guix-kernel
license: GPL 3+
synopsis: Guix kernel for Jupyter  
description: Guix-Jupyter is a Jupyter kernel.  It allows you to annotate
+ notebooks with information about their software dependencies, such that code
+ is executed in the right software environment.  Guix-Jupyter spawns the actual
+ kernels such as `python-ipykernel' on behalf of the notebook user and runs
+ them in an isolated environment, in separate namespaces.
relevance: 13

name: python2-jupyter-core
version: 4.4.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6587:2
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Jupyter base package  
description: Jupyter core is the base package on which Jupyter projects rely.
relevance: 11

name: python2-jupyter-console
version: 5.2.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-ipykernel@4.10.1 python2-jupyter-client@5.2.4
+ python2-nose@1.3.7 python2-prompt-toolkit@1.0.15 python2-pygments@2.5.2
location: gnu/packages/python-xyz.scm:9816:2
homepage: https://jupyter.org
license: Modified BSD
synopsis: Jupyter terminal console  
description: This package provides a terminal-based console frontend for
+ Jupyter kernels.  It also allows for console-based interaction with non-Python
+ Jupyter kernels such as IJulia and IRKernel.
relevance: 11

name: python-jupyter-core
version: 4.4.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6587:2
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Jupyter base package  
description: Jupyter core is the base package on which Jupyter projects rely.
relevance: 11

name: python-jupyter-console
version: 6.1.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipykernel@5.1.3 python-jupyter-client@5.2.4
+ python-nose@1.3.7 python-prompt-toolkit@2.0.7 python-pygments@2.5.2
location: gnu/packages/python-xyz.scm:9789:2
homepage: https://jupyter.org
license: Modified BSD
synopsis: Jupyter terminal console  
description: This package provides a terminal-based console frontend for
+ Jupyter kernels.  It also allows for console-based interaction with non-Python
+ Jupyter kernels such as IJulia and IRKernel.
relevance: 11

name: jupyter-guile-kernel
version: 0.0.0-2.f25fb90
outputs: out
systems: x86_64-linux i686-linux
dependencies: guile-json@3.5.0 guile-simple-zmq@0.0.0-3.68bedb6 guile@3.0.2
+ openssl@1.1.1f
location: gnu/packages/guile-xyz.scm:976:4
homepage: https://github.com/jerry40/guile-kernel
license: GPL 3+
synopsis: Guile kernel for the Jupyter Notebook  
description: This package provides a Guile 2.x kernel for the Jupyter
+ Notebook.  It allows users to interact with the Guile REPL through Jupyter.
relevance: 11

name: python-pari-jupyter
version: 1.3.2
outputs: out
systems: x86_64-linux i686-linux
dependencies: pari-gp@2.11.4 python-ipykernel@5.1.3 readline@8.0.4
location: gnu/packages/python-xyz.scm:6731:2
homepage: https://github.com/jdemeyer/pari_jupyter
license: GPL 3+
synopsis: A Jupyter kernel for PARI/GP  
description: The package provides a PARI/GP kernel for Jupyter.
relevance: 9

name: r-irkernel
version: 1.1.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: jupyter@1.0.0 r-crayon@1.3.4 r-digest@0.6.25 r-evaluate@0.14
+ r-irdisplay@0.7.0 r-jsonlite@1.7.0 r-minimal@4.0.2 r-pbdzmq@0.3-3 r-repr@1.1.0
+ r-uuid@0.1-4
location: gnu/packages/cran.scm:13147:2
homepage: https://cran.r-project.org/web/packages/IRkernel/
license: Expat
synopsis: Native R kernel for Jupyter  
description: The R kernel for the Jupyter environment executes R code which
+ the front-end (Jupyter Notebook or other front-ends) submits to the kernel via
+ the network.
relevance: 7

name: r-irdisplay
version: 0.7.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: r-repr@1.1.0
location: gnu/packages/cran.scm:13124:2
homepage: https://cran.r-project.org/web/packages/IRdisplay/
license: Expat
synopsis: Jupyter display machinery  
description: This package provides an interface to the rich display
+ capabilities of Jupyter front-ends (e.g.  Jupyter Notebook).  It is designed
+ to be used from a running IRkernel session.
relevance: 7

name: ruby-iruby
version: 0.3
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipython@7.9.0 ruby-bond@0.5.1 ruby-cztop@0.12.2
+ ruby-data_uri@0.1.0 ruby-mimemagic@0.3.3 ruby-multi-json@1.13.1
+ ruby-pry@0.13.1
location: gnu/packages/ruby.scm:473:2
homepage: https://github.com/SciRuby/iruby
license: Expat
synopsis: Ruby kernel for Jupyter/IPython  
description: This package provides a Ruby kernel for Jupyter/IPython frontends
+ (e.g.  notebook).
relevance: 5

name: r-nbconvertr
version: 1.3.2
outputs: out
systems: x86_64-linux i686-linux
dependencies: pandoc@2.7.3 python-nbconvert@5.0.0b1
location: gnu/packages/cran.scm:21907:2
homepage: https://cran.r-project.org/web/packages/nbconvertR/
license: GPL 3
synopsis: Vignette engine wrapping Jupyter notebooks  
description: This package calls the Jupyter script `nbconvert' to create
+ vignettes from notebooks.  Those notebooks (`.ipynb' files) are files
+ containing rich text, code, and its output.  Code cells can be edited and
+ evaluated interactively.
relevance: 5

name: python2-widgetsnbextension
version: 3.5.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-certifi@2020.4.5.1 python2-ipykernel@4.10.1
+ python2-nose@1.3.7 python2-notebook@5.7.4
location: gnu/packages/python-xyz.scm:9732:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython HTML widgets for Jupyter  
description: This package provides interactive HTML widgets for Jupyter
+ notebooks.
relevance: 5

name: python2-nbformat
version: 4.4.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-ipython-genutils@0.1.0 python2-jsonschema@3.2.0
+ python2-jupyter-core@4.4.0 python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:9440:2
homepage: http://jupyter.org
license: Modified BSD
synopsis: Jupyter Notebook format  
description: This package provides the reference implementation of the Jupyter
+ Notebook format and Python APIs for working with notebooks.
relevance: 5

name: python2-nbconvert
version: 5.0.0b1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-bleach@3.1.5 python2-entrypoints@0.3
+ python2-jinja2@2.11.2 python2-jupyter-core@4.4.0 python2-mistune@0.8.4
+ python2-nbformat@4.4.0 python2-pygments@2.5.2 python2-pytest@4.6.9
+ python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:9613:2
homepage: http://jupyter.org
license: Modified BSD
synopsis: Converting Jupyter Notebooks  
description: The `nbconvert' tool, {jupyter nbconvert
relevance: 5

name: python2-ipywidgets
version: 7.5.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-ipython@5.8.0 python2-nose@1.3.7 python2-pytest@4.6.9
+ python2-traitlets@4.3.3 python2-widgetsnbextension@3.5.1
location: gnu/packages/python-xyz.scm:9759:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython HTML widgets for Jupyter  
description: Ipywidgets are interactive HTML widgets for Jupyter notebooks and
+ the IPython kernel.  Notebooks come alive when interactive widgets are used.
+ Users gain control of their data and can visualize changes in the data.
relevance: 5

name: python2-ipykernel
version: 4.10.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-ipython@5.8.0 python2-jupyter-client@5.2.4
+ python2-mock@3.0.5 python2-nose@1.3.7 python2-pytest-cov@2.8.1
+ python2-pytest@4.6.9 python2-tornado@5.1.1 python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6701:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython Kernel for Jupyter  
description: This package provides the IPython kernel for Jupyter.
relevance: 5

name: python-widgetsnbextension
version: 3.5.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-certifi@2020.4.5.1 python-ipykernel@5.1.3
+ python-nose@1.3.7 python-notebook@5.7.4
location: gnu/packages/python-xyz.scm:9732:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython HTML widgets for Jupyter  
description: This package provides interactive HTML widgets for Jupyter
+ notebooks.
relevance: 5

name: python-slurm-magic
version: 0.0-0.73dd1a2
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipython@7.9.0 python-pandas@1.0.5 slurm@19.05.3-2
location: gnu/packages/parallel.scm:225:4
homepage: https://github.com/NERSC/slurm-magic
license: Modified BSD
synopsis: Control the SLURM batch scheduler from Jupyter Notebook  
description: This package implements Jupyter/IPython magic commands
+ (http://ipython.readthedocs.io/en/stable/interactive/magics.html) for
+ interacting with the SLURM workload manager.  SLURM magic simply wraps
+ command-line executables and the commands themselves should look like their
+ command-line counterparts.  Commands are spawned via `subprocess' and output
+ captured in the notebook.  Whatever arguments are accepted by a SLURM command
+ line executable are also accepted by the corresponding magic command---e.g.,
+ `%salloc', `%sbatch', etc.
relevance: 5

name: python-qtconsole
version: 4.4.3
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipykernel@5.1.3 python-ipython@7.9.0 python-pytest@5.3.5
location: gnu/packages/python-xyz.scm:9871:2
homepage: http://jupyter.org
license: Modified BSD
synopsis: Jupyter Qt console  
description: This package provides a Qt-based console for Jupyter with support
+ for rich media output.
relevance: 5

name: python-nbval
version: 0.9.6
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipykernel@5.1.3 python-jupyter-client@5.2.4
+ python-nbformat@4.4.0 python-pytest-cov@2.8.1 python-pytest@5.3.5
+ python-six@1.14.0 python-sympy@1.1.1
location: gnu/packages/python-check.scm:766:2
homepage: https://github.com/computationalmodelling/nbval
license: Modified BSD
synopsis: Pytest plugin to validate Jupyter notebooks  
description: This plugin adds functionality to Pytest to recognise and collect
+ Jupyter notebooks.  The intended purpose of the tests is to determine whether
+ execution of the stored inputs match the stored outputs of the `.ipynb' file.
+ Whilst also ensuring that the notebooks are running without errors.
relevance: 5

name: python-nbformat
version: 4.4.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipython-genutils@0.1.0 python-jsonschema@3.2.0
+ python-jupyter-core@4.4.0 python-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:9440:2
homepage: http://jupyter.org
license: Modified BSD
synopsis: Jupyter Notebook format  
description: This package provides the reference implementation of the Jupyter
+ Notebook format and Python APIs for working with notebooks.
relevance: 5

name: python-nbconvert
version: 5.0.0b1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-bleach@3.1.5 python-entrypoints@0.3 python-jinja2@2.11.2
+ python-jupyter-core@4.4.0 python-mistune@0.8.4 python-nbformat@4.4.0
+ python-pygments@2.5.2 python-pytest@5.3.5 python-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:9613:2
homepage: http://jupyter.org
license: Modified BSD
synopsis: Converting Jupyter Notebooks  
description: The `nbconvert' tool, {jupyter nbconvert
relevance: 5

name: python-ipywidgets
version: 7.5.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipython@7.9.0 python-nose@1.3.7 python-pytest@5.3.5
+ python-traitlets@4.3.3 python-widgetsnbextension@3.5.1
location: gnu/packages/python-xyz.scm:9759:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython HTML widgets for Jupyter  
description: Ipywidgets are interactive HTML widgets for Jupyter notebooks and
+ the IPython kernel.  Notebooks come alive when interactive widgets are used.
+ Users gain control of their data and can visualize changes in the data.
relevance: 5

name: python-ipykernel
version: 5.1.3
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-flaky@3.5.3 python-ipython@7.9.0
+ python-jupyter-client@5.2.4 python-nose@1.3.7 python-pytest@5.3.5
location: gnu/packages/python-xyz.scm:6656:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython Kernel for Jupyter  
description: This package provides the IPython kernel for Jupyter.
relevance: 5

name: ghc-ipynb
version: 0.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: ghc-aeson-diff@1.1.0.7 ghc-aeson@1.4.5.0
+ ghc-base64-bytestring@1.0.0.2 ghc-microlens-aeson@2.3.0.4 ghc-microlens@0.4.10
+ ghc-semigroups@0.18.5 ghc-tasty-hunit@0.10.0.2 ghc-tasty@1.2.3
+ ghc-unordered-containers@0.2.10.0 ghc-vector@0.12.0.3
location: gnu/packages/haskell-xyz.scm:6474:2
homepage: https://hackage.haskell.org/package/ipynb
license: Modified BSD
synopsis: Data structure for working with Jupyter notebooks  
description: This library defines a data structure for representing Jupyter
+ notebooks, along with `ToJSON' and `FromJSON' instances for conversion to and
+ from JSON .ipynb files.
relevance: 5

name: python2-ipython-genutils
version: 0.1.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: 
location: gnu/packages/python-xyz.scm:6413:2
homepage: https://ipython.org
license: Modified BSD
synopsis: Vestigial utilities from IPython  
description: This package provides retired utilities from IPython.  No
+ packages outside IPython/Jupyter should depend on it.
+ 
+ This package shouldn't exist.  It contains some common utilities shared by
+ Jupyter and IPython projects during The Big Split.  As soon as possible, those
+ packages will remove their dependency on this, and this package will go away.
relevance: 4

name: python-ipython-genutils
version: 0.1.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: 
location: gnu/packages/python-xyz.scm:6413:2
homepage: https://ipython.org
license: Modified BSD
synopsis: Vestigial utilities from IPython  
description: This package provides retired utilities from IPython.  No
+ packages outside IPython/Jupyter should depend on it.
+ 
+ This package shouldn't exist.  It contains some common utilities shared by
+ Jupyter and IPython projects during The Big Split.  As soon as possible, those
+ packages will remove their dependency on this, and this package will go away.
relevance: 4

name: python2-notebook
version: 5.7.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-jupyter-core@4.4.0 python2-mock@3.0.5
+ python2-nbconvert@5.0.0b1 python2-nbformat@4.4.0 python2-nose@1.3.7
+ python2-prometheus-client@0.7.1 python2-requests@2.23.0
+ python2-send2trash@1.5.0 python2-sphinx@1.7.7 python2-terminado@0.8.1
location: gnu/packages/python-xyz.scm:9714:4
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Web-based notebook environment for interactive computing  
description: The Jupyter HTML notebook is a web-based notebook environment for
+ interactive computing.
relevance: 2

name: python2-ipyparallel
version: 6.2.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-dateutil@2.8.1 python2-decorator@4.3.0
+ python2-futures@3.2.0 python2-ipykernel@4.10.1 python2-ipython-genutils@0.1.0
+ python2-ipython@5.8.0 python2-jupyter-client@5.2.4 python2-mock@3.0.5
+ python2-nose@1.3.7 python2-pytest-cov@2.8.1 python2-pytest@4.6.9
+ python2-pyzmq@17.1.2 python2-testpath@0.2 python2-tornado@5.1.1
+ python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6491:4
homepage: https://ipython.org/
license: Modified BSD
synopsis: Interactive Parallel Computing with IPython  
description: `ipyparallel' is a Python package and collection of CLI scripts
+ for controlling clusters for Jupyter.  `ipyparallel' contains the following
+ CLI scripts:
+ 
+   1. ipcluster - start/stop a cluster
+ 
+   2. ipcontroller - start a scheduler
+ 
+   3. ipengine - start an engine
relevance: 2

name: python-notebook
version: 5.7.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-jupyter-core@4.4.0 python-nbconvert@5.0.0b1
+ python-nbformat@4.4.0 python-nose@1.3.7 python-prometheus-client@0.7.1
+ python-requests@2.23.0 python-send2trash@1.5.0 python-sphinx@2.3.1
+ python-terminado@0.8.1
location: gnu/packages/python-xyz.scm:9667:2
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Web-based notebook environment for interactive computing  
description: The Jupyter HTML notebook is a web-based notebook environment for
+ interactive computing.
relevance: 2

name: python-ipyparallel
version: 6.2.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-dateutil@2.8.1 python-decorator@4.3.0
+ python-ipykernel@5.1.3 python-ipython-genutils@0.1.0 python-ipython@7.9.0
+ python-jupyter-client@5.2.4 python-mock@3.0.5 python-nose@1.3.7
+ python-pytest-cov@2.8.1 python-pytest@5.3.5 python-pyzmq@17.1.2
+ python-testpath@0.2 python-tornado@5.1.1 python-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6440:2
homepage: https://ipython.org/
license: Modified BSD
synopsis: Interactive Parallel Computing with IPython  
description: `ipyparallel' is a Python package and collection of CLI scripts
+ for controlling clusters for Jupyter.  `ipyparallel' contains the following
+ CLI scripts:
+ 
+   1. ipcluster - start/stop a cluster
+ 
+   2. ipcontroller - start a scheduler
+ 
+   3. ipengine - start an engine
relevance: 2

#+end_example

C'est déjà prometteur, mais voyons comme proposé la totalité des résultats. Dans Emacs, nous remplaçons =less= par =cat=:

#+begin_src sh :results output :exports both
guix search jupyter | cat
#+end_src

#+RESULTS:
#+begin_example
name: jupyter
version: 1.0.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipykernel@5.1.3 python-ipywidgets@7.5.1
+ python-jupyter-console@6.1.0 python-nbconvert@5.0.0b1 python-notebook@5.7.4
+ python-qtconsole@4.4.3
location: gnu/packages/python-xyz.scm:9946:2
homepage: https://jupyter.org
license: Modified BSD
synopsis: Web application for interactive documents  
description: The Jupyter Notebook is a web application that allows you to
+ create and share documents that contain live code, equations, visualizations
+ and explanatory text.  Uses include: data cleaning and transformation,
+ numerical simulation, statistical modeling, machine learning and much more.
relevance: 22

name: python-jupyter-kernel-test
version: 0.3
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-jsonschema@3.2.0 python-jupyter-kernel-mgmt@0.4.0
+ python-jupyter-protocol@0.1.1
location: gnu/packages/jupyter.scm:98:2
homepage: https://github.com/jupyter/jupyter_kernel_test
license: Modified BSD
synopsis: Test Jupyter kernels  
description: `jupyter_kernel_test' is a tool for testing Jupyter kernels.  It
+ tests kernels for successful code execution and conformance with the Jupyter
+ Messaging Protocol
+ (https://jupyter-client.readthedocs.io/en/latest/messaging.html).
relevance: 20

name: xeus
version: 0.23.2
outputs: out
systems: x86_64-linux i686-linux
dependencies: cppzmq@4.6.0 googletest@1.10.0 json-modern-cxx@3.9.1
+ openssl@1.1.1f pkg-config@0.29.2 python-jupyter-client@5.2.4
+ python-jupyter-kernel-test@0.3 python-pytest@5.3.5 python@3.8.2
+ util-linux@2.35.1 xtl@0.6.18 zeromq@4.3.2
location: gnu/packages/jupyter.scm:142:2
homepage: https://quantstack.net/xeus
license: Modified BSD
synopsis: C++ implementation of the Jupyter Kernel protocol  
description: `xeus' is a library meant to facilitate the implementation of
+ kernels for Jupyter.  It takes the burden of implementing the Jupyter Kernel
+ protocol so developers can focus on implementing the interpreter part of the
+ kernel.
+ 
+ Several Jupyter kernels are built upon `xeus', such as `xeus-cling', a kernel
+ for the C++ programming language, and `xeus-python', an alternative Python
+ kernel for Jupyter.
relevance: 16

name: python-jupyter-protocol
version: 0.1.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-dateutil@2.8.1 python-ipykernel@5.1.3
+ python-ipython@7.9.0 python-jupyter-core@4.4.0 python-mock@3.0.5
+ python-pytest@5.3.5 python-pyzmq@17.1.2 python-traitlets@4.3.3
location: gnu/packages/jupyter.scm:37:2
homepage: https://jupyter.org
license: Modified BSD
synopsis: Jupyter protocol implementation  
description: This Python library is an experimental implementation of the
+ Jupyter protocol
+ (https://jupyter-client.readthedocs.io/en/latest/messaging.html) to be used by
+ both clients and kernels.
relevance: 16

name: python2-jupyter-client
version: 5.2.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: iproute2@5.8.0 python2-jupyter-core@4.4.0 python2-pyzmq@17.1.2
+ python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6612:2
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Jupyter protocol implementation and client libraries  
description: The `jupyter_client' package contains the reference
+ implementation of the Jupyter protocol.  It also provides client and kernel
+ management APIs for working with kernels, and the `jupyter kernelspec'
+ entrypoint for installing `kernelspec's for use with Jupyter frontends.
relevance: 15

name: python-jupyter-client
version: 5.2.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: iproute2@5.8.0 python-jupyter-core@4.4.0 python-pyzmq@17.1.2
+ python-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6612:2
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Jupyter protocol implementation and client libraries  
description: The `jupyter_client' package contains the reference
+ implementation of the Jupyter protocol.  It also provides client and kernel
+ management APIs for working with kernels, and the `jupyter kernelspec'
+ entrypoint for installing `kernelspec's for use with Jupyter frontends.
relevance: 15

name: python-jupyter-kernel-mgmt
version: 0.4.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-dateutil@2.8.1 python-entrypoints@0.3
+ python-ipykernel@5.1.3 python-ipython@7.9.0 python-jupyter-core@4.4.0
+ python-jupyter-protocol@0.1.1 python-mock@3.0.5 python-pytest@5.3.5
+ python-pyzmq@17.1.2 python-traitlets@4.3.3
location: gnu/packages/jupyter.scm:67:2
homepage: https://jupyter.org
license: Modified BSD
synopsis: Discover, launch, and communicate with Jupyter kernels  
description: This package is an experimental refactoring of the machinery for
+ launching and using Jupyter kernels.
relevance: 14

name: guix-jupyter
version: 0.1.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: autoconf@2.69 automake@1.16.2 guile-gcrypt@0.3.0
+ guile-json@4.3.2 guile-simple-zmq@0.0.0-3.68bedb6 guile@3.0.4
+ guix@1.1.0-25.44c6e6f jupyter@1.0.0 pkg-config@0.29.2 python-ipykernel@5.1.3
+ python-ipython@7.9.0
location: gnu/packages/package-management.scm:985:2
homepage: https://gitlab.inria.fr/guix-hpc/guix-kernel
license: GPL 3+
synopsis: Guix kernel for Jupyter  
description: Guix-Jupyter is a Jupyter kernel.  It allows you to annotate
+ notebooks with information about their software dependencies, such that code
+ is executed in the right software environment.  Guix-Jupyter spawns the actual
+ kernels such as `python-ipykernel' on behalf of the notebook user and runs
+ them in an isolated environment, in separate namespaces.
relevance: 13

name: python2-jupyter-core
version: 4.4.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6587:2
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Jupyter base package  
description: Jupyter core is the base package on which Jupyter projects rely.
relevance: 11

name: python2-jupyter-console
version: 5.2.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-ipykernel@4.10.1 python2-jupyter-client@5.2.4
+ python2-nose@1.3.7 python2-prompt-toolkit@1.0.15 python2-pygments@2.5.2
location: gnu/packages/python-xyz.scm:9816:2
homepage: https://jupyter.org
license: Modified BSD
synopsis: Jupyter terminal console  
description: This package provides a terminal-based console frontend for
+ Jupyter kernels.  It also allows for console-based interaction with non-Python
+ Jupyter kernels such as IJulia and IRKernel.
relevance: 11

name: python-jupyter-core
version: 4.4.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6587:2
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Jupyter base package  
description: Jupyter core is the base package on which Jupyter projects rely.
relevance: 11

name: python-jupyter-console
version: 6.1.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipykernel@5.1.3 python-jupyter-client@5.2.4
+ python-nose@1.3.7 python-prompt-toolkit@2.0.7 python-pygments@2.5.2
location: gnu/packages/python-xyz.scm:9789:2
homepage: https://jupyter.org
license: Modified BSD
synopsis: Jupyter terminal console  
description: This package provides a terminal-based console frontend for
+ Jupyter kernels.  It also allows for console-based interaction with non-Python
+ Jupyter kernels such as IJulia and IRKernel.
relevance: 11

name: jupyter-guile-kernel
version: 0.0.0-2.f25fb90
outputs: out
systems: x86_64-linux i686-linux
dependencies: guile-json@3.5.0 guile-simple-zmq@0.0.0-3.68bedb6 guile@3.0.2
+ openssl@1.1.1f
location: gnu/packages/guile-xyz.scm:976:4
homepage: https://github.com/jerry40/guile-kernel
license: GPL 3+
synopsis: Guile kernel for the Jupyter Notebook  
description: This package provides a Guile 2.x kernel for the Jupyter
+ Notebook.  It allows users to interact with the Guile REPL through Jupyter.
relevance: 11

name: python-pari-jupyter
version: 1.3.2
outputs: out
systems: x86_64-linux i686-linux
dependencies: pari-gp@2.11.4 python-ipykernel@5.1.3 readline@8.0.4
location: gnu/packages/python-xyz.scm:6731:2
homepage: https://github.com/jdemeyer/pari_jupyter
license: GPL 3+
synopsis: A Jupyter kernel for PARI/GP  
description: The package provides a PARI/GP kernel for Jupyter.
relevance: 9

name: r-irkernel
version: 1.1.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: jupyter@1.0.0 r-crayon@1.3.4 r-digest@0.6.25 r-evaluate@0.14
+ r-irdisplay@0.7.0 r-jsonlite@1.7.0 r-minimal@4.0.2 r-pbdzmq@0.3-3 r-repr@1.1.0
+ r-uuid@0.1-4
location: gnu/packages/cran.scm:13147:2
homepage: https://cran.r-project.org/web/packages/IRkernel/
license: Expat
synopsis: Native R kernel for Jupyter  
description: The R kernel for the Jupyter environment executes R code which
+ the front-end (Jupyter Notebook or other front-ends) submits to the kernel via
+ the network.
relevance: 7

name: r-irdisplay
version: 0.7.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: r-repr@1.1.0
location: gnu/packages/cran.scm:13124:2
homepage: https://cran.r-project.org/web/packages/IRdisplay/
license: Expat
synopsis: Jupyter display machinery  
description: This package provides an interface to the rich display
+ capabilities of Jupyter front-ends (e.g.  Jupyter Notebook).  It is designed
+ to be used from a running IRkernel session.
relevance: 7

name: ruby-iruby
version: 0.3
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipython@7.9.0 ruby-bond@0.5.1 ruby-cztop@0.12.2
+ ruby-data_uri@0.1.0 ruby-mimemagic@0.3.3 ruby-multi-json@1.13.1
+ ruby-pry@0.13.1
location: gnu/packages/ruby.scm:473:2
homepage: https://github.com/SciRuby/iruby
license: Expat
synopsis: Ruby kernel for Jupyter/IPython  
description: This package provides a Ruby kernel for Jupyter/IPython frontends
+ (e.g.  notebook).
relevance: 5

name: r-nbconvertr
version: 1.3.2
outputs: out
systems: x86_64-linux i686-linux
dependencies: pandoc@2.7.3 python-nbconvert@5.0.0b1
location: gnu/packages/cran.scm:21907:2
homepage: https://cran.r-project.org/web/packages/nbconvertR/
license: GPL 3
synopsis: Vignette engine wrapping Jupyter notebooks  
description: This package calls the Jupyter script `nbconvert' to create
+ vignettes from notebooks.  Those notebooks (`.ipynb' files) are files
+ containing rich text, code, and its output.  Code cells can be edited and
+ evaluated interactively.
relevance: 5

name: python2-widgetsnbextension
version: 3.5.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-certifi@2020.4.5.1 python2-ipykernel@4.10.1
+ python2-nose@1.3.7 python2-notebook@5.7.4
location: gnu/packages/python-xyz.scm:9732:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython HTML widgets for Jupyter  
description: This package provides interactive HTML widgets for Jupyter
+ notebooks.
relevance: 5

name: python2-nbformat
version: 4.4.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-ipython-genutils@0.1.0 python2-jsonschema@3.2.0
+ python2-jupyter-core@4.4.0 python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:9440:2
homepage: http://jupyter.org
license: Modified BSD
synopsis: Jupyter Notebook format  
description: This package provides the reference implementation of the Jupyter
+ Notebook format and Python APIs for working with notebooks.
relevance: 5

name: python2-nbconvert
version: 5.0.0b1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-bleach@3.1.5 python2-entrypoints@0.3
+ python2-jinja2@2.11.2 python2-jupyter-core@4.4.0 python2-mistune@0.8.4
+ python2-nbformat@4.4.0 python2-pygments@2.5.2 python2-pytest@4.6.9
+ python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:9613:2
homepage: http://jupyter.org
license: Modified BSD
synopsis: Converting Jupyter Notebooks  
description: The `nbconvert' tool, {jupyter nbconvert
relevance: 5

name: python2-ipywidgets
version: 7.5.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-ipython@5.8.0 python2-nose@1.3.7 python2-pytest@4.6.9
+ python2-traitlets@4.3.3 python2-widgetsnbextension@3.5.1
location: gnu/packages/python-xyz.scm:9759:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython HTML widgets for Jupyter  
description: Ipywidgets are interactive HTML widgets for Jupyter notebooks and
+ the IPython kernel.  Notebooks come alive when interactive widgets are used.
+ Users gain control of their data and can visualize changes in the data.
relevance: 5

name: python2-ipykernel
version: 4.10.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-ipython@5.8.0 python2-jupyter-client@5.2.4
+ python2-mock@3.0.5 python2-nose@1.3.7 python2-pytest-cov@2.8.1
+ python2-pytest@4.6.9 python2-tornado@5.1.1 python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6701:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython Kernel for Jupyter  
description: This package provides the IPython kernel for Jupyter.
relevance: 5

name: python-widgetsnbextension
version: 3.5.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-certifi@2020.4.5.1 python-ipykernel@5.1.3
+ python-nose@1.3.7 python-notebook@5.7.4
location: gnu/packages/python-xyz.scm:9732:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython HTML widgets for Jupyter  
description: This package provides interactive HTML widgets for Jupyter
+ notebooks.
relevance: 5

name: python-slurm-magic
version: 0.0-0.73dd1a2
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipython@7.9.0 python-pandas@1.0.5 slurm@19.05.3-2
location: gnu/packages/parallel.scm:225:4
homepage: https://github.com/NERSC/slurm-magic
license: Modified BSD
synopsis: Control the SLURM batch scheduler from Jupyter Notebook  
description: This package implements Jupyter/IPython magic commands
+ (http://ipython.readthedocs.io/en/stable/interactive/magics.html) for
+ interacting with the SLURM workload manager.  SLURM magic simply wraps
+ command-line executables and the commands themselves should look like their
+ command-line counterparts.  Commands are spawned via `subprocess' and output
+ captured in the notebook.  Whatever arguments are accepted by a SLURM command
+ line executable are also accepted by the corresponding magic command---e.g.,
+ `%salloc', `%sbatch', etc.
relevance: 5

name: python-qtconsole
version: 4.4.3
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipykernel@5.1.3 python-ipython@7.9.0 python-pytest@5.3.5
location: gnu/packages/python-xyz.scm:9871:2
homepage: http://jupyter.org
license: Modified BSD
synopsis: Jupyter Qt console  
description: This package provides a Qt-based console for Jupyter with support
+ for rich media output.
relevance: 5

name: python-nbval
version: 0.9.6
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipykernel@5.1.3 python-jupyter-client@5.2.4
+ python-nbformat@4.4.0 python-pytest-cov@2.8.1 python-pytest@5.3.5
+ python-six@1.14.0 python-sympy@1.1.1
location: gnu/packages/python-check.scm:766:2
homepage: https://github.com/computationalmodelling/nbval
license: Modified BSD
synopsis: Pytest plugin to validate Jupyter notebooks  
description: This plugin adds functionality to Pytest to recognise and collect
+ Jupyter notebooks.  The intended purpose of the tests is to determine whether
+ execution of the stored inputs match the stored outputs of the `.ipynb' file.
+ Whilst also ensuring that the notebooks are running without errors.
relevance: 5

name: python-nbformat
version: 4.4.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipython-genutils@0.1.0 python-jsonschema@3.2.0
+ python-jupyter-core@4.4.0 python-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:9440:2
homepage: http://jupyter.org
license: Modified BSD
synopsis: Jupyter Notebook format  
description: This package provides the reference implementation of the Jupyter
+ Notebook format and Python APIs for working with notebooks.
relevance: 5

name: python-nbconvert
version: 5.0.0b1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-bleach@3.1.5 python-entrypoints@0.3 python-jinja2@2.11.2
+ python-jupyter-core@4.4.0 python-mistune@0.8.4 python-nbformat@4.4.0
+ python-pygments@2.5.2 python-pytest@5.3.5 python-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:9613:2
homepage: http://jupyter.org
license: Modified BSD
synopsis: Converting Jupyter Notebooks  
description: The `nbconvert' tool, {jupyter nbconvert
relevance: 5

name: python-ipywidgets
version: 7.5.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-ipython@7.9.0 python-nose@1.3.7 python-pytest@5.3.5
+ python-traitlets@4.3.3 python-widgetsnbextension@3.5.1
location: gnu/packages/python-xyz.scm:9759:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython HTML widgets for Jupyter  
description: Ipywidgets are interactive HTML widgets for Jupyter notebooks and
+ the IPython kernel.  Notebooks come alive when interactive widgets are used.
+ Users gain control of their data and can visualize changes in the data.
relevance: 5

name: python-ipykernel
version: 5.1.3
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-flaky@3.5.3 python-ipython@7.9.0
+ python-jupyter-client@5.2.4 python-nose@1.3.7 python-pytest@5.3.5
location: gnu/packages/python-xyz.scm:6656:2
homepage: https://ipython.org
license: Modified BSD
synopsis: IPython Kernel for Jupyter  
description: This package provides the IPython kernel for Jupyter.
relevance: 5

name: ghc-ipynb
version: 0.1
outputs: out
systems: x86_64-linux i686-linux
dependencies: ghc-aeson-diff@1.1.0.7 ghc-aeson@1.4.5.0
+ ghc-base64-bytestring@1.0.0.2 ghc-microlens-aeson@2.3.0.4 ghc-microlens@0.4.10
+ ghc-semigroups@0.18.5 ghc-tasty-hunit@0.10.0.2 ghc-tasty@1.2.3
+ ghc-unordered-containers@0.2.10.0 ghc-vector@0.12.0.3
location: gnu/packages/haskell-xyz.scm:6474:2
homepage: https://hackage.haskell.org/package/ipynb
license: Modified BSD
synopsis: Data structure for working with Jupyter notebooks  
description: This library defines a data structure for representing Jupyter
+ notebooks, along with `ToJSON' and `FromJSON' instances for conversion to and
+ from JSON .ipynb files.
relevance: 5

name: python2-ipython-genutils
version: 0.1.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: 
location: gnu/packages/python-xyz.scm:6413:2
homepage: https://ipython.org
license: Modified BSD
synopsis: Vestigial utilities from IPython  
description: This package provides retired utilities from IPython.  No
+ packages outside IPython/Jupyter should depend on it.
+ 
+ This package shouldn't exist.  It contains some common utilities shared by
+ Jupyter and IPython projects during The Big Split.  As soon as possible, those
+ packages will remove their dependency on this, and this package will go away.
relevance: 4

name: python-ipython-genutils
version: 0.1.0
outputs: out
systems: x86_64-linux i686-linux
dependencies: 
location: gnu/packages/python-xyz.scm:6413:2
homepage: https://ipython.org
license: Modified BSD
synopsis: Vestigial utilities from IPython  
description: This package provides retired utilities from IPython.  No
+ packages outside IPython/Jupyter should depend on it.
+ 
+ This package shouldn't exist.  It contains some common utilities shared by
+ Jupyter and IPython projects during The Big Split.  As soon as possible, those
+ packages will remove their dependency on this, and this package will go away.
relevance: 4

name: python2-notebook
version: 5.7.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-jupyter-core@4.4.0 python2-mock@3.0.5
+ python2-nbconvert@5.0.0b1 python2-nbformat@4.4.0 python2-nose@1.3.7
+ python2-prometheus-client@0.7.1 python2-requests@2.23.0
+ python2-send2trash@1.5.0 python2-sphinx@1.7.7 python2-terminado@0.8.1
location: gnu/packages/python-xyz.scm:9714:4
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Web-based notebook environment for interactive computing  
description: The Jupyter HTML notebook is a web-based notebook environment for
+ interactive computing.
relevance: 2

name: python2-ipyparallel
version: 6.2.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: python2-dateutil@2.8.1 python2-decorator@4.3.0
+ python2-futures@3.2.0 python2-ipykernel@4.10.1 python2-ipython-genutils@0.1.0
+ python2-ipython@5.8.0 python2-jupyter-client@5.2.4 python2-mock@3.0.5
+ python2-nose@1.3.7 python2-pytest-cov@2.8.1 python2-pytest@4.6.9
+ python2-pyzmq@17.1.2 python2-testpath@0.2 python2-tornado@5.1.1
+ python2-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6491:4
homepage: https://ipython.org/
license: Modified BSD
synopsis: Interactive Parallel Computing with IPython  
description: `ipyparallel' is a Python package and collection of CLI scripts
+ for controlling clusters for Jupyter.  `ipyparallel' contains the following
+ CLI scripts:
+ 
+   1. ipcluster - start/stop a cluster
+ 
+   2. ipcontroller - start a scheduler
+ 
+   3. ipengine - start an engine
relevance: 2

name: python-notebook
version: 5.7.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-jupyter-core@4.4.0 python-nbconvert@5.0.0b1
+ python-nbformat@4.4.0 python-nose@1.3.7 python-prometheus-client@0.7.1
+ python-requests@2.23.0 python-send2trash@1.5.0 python-sphinx@2.3.1
+ python-terminado@0.8.1
location: gnu/packages/python-xyz.scm:9667:2
homepage: http://jupyter.org/
license: Modified BSD
synopsis: Web-based notebook environment for interactive computing  
description: The Jupyter HTML notebook is a web-based notebook environment for
+ interactive computing.
relevance: 2

name: python-ipyparallel
version: 6.2.4
outputs: out
systems: x86_64-linux i686-linux
dependencies: python-dateutil@2.8.1 python-decorator@4.3.0
+ python-ipykernel@5.1.3 python-ipython-genutils@0.1.0 python-ipython@7.9.0
+ python-jupyter-client@5.2.4 python-mock@3.0.5 python-nose@1.3.7
+ python-pytest-cov@2.8.1 python-pytest@5.3.5 python-pyzmq@17.1.2
+ python-testpath@0.2 python-tornado@5.1.1 python-traitlets@4.3.3
location: gnu/packages/python-xyz.scm:6440:2
homepage: https://ipython.org/
license: Modified BSD
synopsis: Interactive Parallel Computing with IPython  
description: `ipyparallel' is a Python package and collection of CLI scripts
+ for controlling clusters for Jupyter.  `ipyparallel' contains the following
+ CLI scripts:
+ 
+   1. ipcluster - start/stop a cluster
+ 
+   2. ipcontroller - start a scheduler
+ 
+   3. ipengine - start an engine
relevance: 2

#+end_example

Aouch ! Ça fait beaucoup. Dans le tas, il y a un paquet qui s'appelle
=jupyter=. C'est un bon point de départ. Installons-le et voyons ce qu'on peut faire avec. Attention, ce qui se passe quand vous lancez la commande suivante peut être très variable. Dans le meilleur cas, Guix télécharge une version précompilée de Jupyter. Au pire, Guix compile Jupyter à partir de son code source. Et si vous n'avez vraiment pas de chance, Guix va d'abord compiler juste la bonne version des compilateurs qu'il faut pour compiler Jupyter. Dans ce cas, vous devez attendre longtemps - mais à la fin, vous aurez ce que vous avez demandé.

Alors... allons-y !
#+begin_src sh :results output :exports both
guix install jupyter
#+end_src

#+RESULTS:

Ceux qui ont l'habitude d'une distribution classique étaient peut-être tentés de rajouter =sudo= devant la commande, parce que l'installation d'un logiciel, ça relève des privilèges d'un administrateur. Ce n'est pas le cas avec Guix. Sous Guix, chaque utilisateur gère ses logiciels de façon autonome. Le =jupyter= que je viens d'installer n'est accessible que pour moi. En fait, l'annonce des "84 paquets dans mon profil" veut dire qu'il y a 84 paquets installés à mon nom, un "profil" étant une collection de paquets installés (et on peut même en avoir plusieurs, mais ça dépasse le cadre de ce tutoriel).

Pour tester, lançons =jupyter=:
#+begin_src sh :results none :exports code
jupyter notebook
#+end_src
Un essai rapide confirme que tout est là pour créer un notebook en langage Python 3, donc tout va bien.

Il reste à faire la même chose avec =matplotlib=, =pandas=, =numpy= et =statsmodels=. Je trouve les noms des paquets avec =guix search=, et puis j'installe tout avec une seule commande :

#+begin_src sh :results output :exports both
guix install python-matplotlib python-numpy python-pandas python-statsmodels
#+end_src

#+RESULTS:

Je rajoute le paquet =python-nbconvert= qui permet de
convertir les notebooks en ligne de commande sans passer par
l'interface graphique, ça peut toujours servir :
#+begin_src sh :results output :exports both
guix install python-nbconvert
#+end_src

#+RESULTS:


** 2.4 Automatiser la construction de son environnement
Vous remarquerez que dans tout ce qui a précédé, j'ai noté dans mon
journal de ce que j'ai effectué mais vous n'avez aucune garantie que
je n'ai rien oublié. De plus, si vous voulez refaire cet environnement
vous-même, il vous faudra suivre ces instructions scrupuleusement en
espérant que rien n'aille de travers.

Je vais donc maintenant introduire alors la notion du =manifest= qui
va réaliser la préparation de l'environnement automatiquement à l'aide
de la commande =guix environment=. Un =manifest= est une spécification
complète d'un environnement de calcul. Voyons à quoi ça ressemble.

g#+RESULTS:

Je crée un fichier [[file:moocrr_guix_jupyter/manifest.scm][moocrr_guix_jupyter/manifest.scm]] dont voici
le contenu.

#+begin_src guile :exports both :tangle moocrr_guix_jupyter/manifest.scm :eval no
(specifications->manifest
 '("jupyter"
   "python-matplotlib"
   "python-numpy"
   "python-pandas"
   "python-statsmodels"
   "python-nbconvert"))
#+end_src

C'est essentiellement la liste des paquets que j'ai installés à la main auparavant, mais dans un format un peu particulier qu'il faut respecter scrupuleusement. En fait, ce format n'est rien d'autre que le langage de programmation [[https://fr.wikipedia.org/wiki/Scheme][Scheme]]. Guix est écrit en Scheme, et exprimer une liste de paquets en Scheme a le grand avantage qu'on peut utiliser des fonctionnalités avancées de Guix pour définir son environnement. Par exemple, je pourrais demander que tous mes paquets, en commençant par Python, soient compilés avec =gcc 7= plutôt qu'avec le compilateur par défaut de Guix, qui est actuellement =gcc 5=.

Je peux alors créer un environnement contenant ces paquets avec :
#+begin_src sh :session *jupyter-env* :results output :exports both :eval no
guix environment --pure -m ./moocrr_guix_jupyter/manifest.scm
#+end_src

Ceci me lance une shell (=bash=, plus précisément) de laquelle Jupyter est accessible et configuré avec tous les modules Python demandés :
#+begin_src sh :session *jupyter-env* :results output :exports both :eval no
jupyter notebook
#+end_src

Mais il est encore plus pratique de lancer directement Jupyter plutôt de passer par une shell :
#+begin_src sh :results output :exports both :eval no
guix environment -m ./moocrr_guix_jupyter/manifest.scm -- jupyter notebook
#+end_src

Pour faire encore mieux, rajoutons l'option =–pure= :
#+begin_src sh :results output :exports both :eval no
guix environment --pure -m ./moocrr_guix_jupyter/manifest.scm -- jupyter notebook
#+end_src

Un environnement "pur" ne contient que les paquets définis dans le manifeste, pendant qu'un environnement "standard" contient aussi tout ce qui est disponible par défaut par la ligne de commande, donc des utilitaires comme =ls=, =cp=, etc. Avec un environnement pur, on est sûr de ne pas utiliser une commande qui n'est pas listée dans le manifeste, même pas par erreur.

** 2.5 Mieux connaître son environnement
J'ai bien choisi les paquets qui seront dans mon environnement, mais je n'ai pas choisi les versions. Contrairement à des gestionnaires de paquet traditionnels, Guix peux gérer plusieurs versions d'un même paquet dans la distribution, et c'est à l'utilisateur de choisir laquelle installer. En pratique, Guix contient seulement la version la plus récente de chaque paquet, pour faciliter la maintenance. Une exception est faite pour quelques paquets particulièrement importants pour lesquels plusieurs versions restent d'actualité. L'exemple typique est =gcc=, la collection des compilateurs GNU. Dans mon environnement, il n'y a rien de cette catégorie. J'ai donc installé les seules versions définies dans l'état actuel de Guix.

Il est pourtant important de savoir quelles versions on utilise, et il est fortement conseillé d'inclure cette information dans toute publication scientifique. La commande pour accéder à ces informations est =guix package -I=. Pour l'exécuter correctement dans mon environnement, je rentre d'abord dans une shell comme montré ci-dessus :
#+begin_src sh :session *guix* :results output :exports both
guix environment -m ./moocrr_guix_jupyter/manifest.scm
#+end_src

#+RESULTS:

Puis je lance ma requête :
#+begin_src sh :session *guix* :results output :exports both
guix package -p $GUIX_ENVIRONMENT -I
#+end_src

#+RESULTS:
: python-nbconvert	5.0.0b1	out	/gnu/store/1xb4jz8bi42w0jm0znxa1cq8jrmdpwgb-python-nbconvert-5.0.0b1
: python-statsmodels	0.11.1	out	/gnu/store/wwk3vf4cfsdn9bzw15sv9aysgc35f2sw-python-statsmodels-0.11.1
: python-pandas	1.0.5	out	/gnu/store/54bg8qnb943npwpw9k0ry0wgx06471b2-python-pandas-1.0.5
: python-numpy	1.17.3	out	/gnu/store/3j2d23kldb7cdzamj9cvg0j7j3fhhari-python-numpy-1.17.3
: python-matplotlib	3.1.2	out	/gnu/store/gsjhzr1xy96hz8wvaa8mblvv2niqnkwy-python-matplotlib-3.1.2
: jupyter	1.0.0	out	/gnu/store/sh1k32zgqddz0n86v13w6kdd61h7634g-jupyter-1.0.0


La dernière colonne montre les répertoires où se trouvent les paquets. Ceci est utile par exemple pour regarder les modules Python qui en font partie.

Reste à comprendre à quoi sert l'argument =-p $GUIX_ENVIRONMENT=. Normalement, l'option =-p= sert à choisir un "profil", ce qui est un environnement permanent. Dans un environnement temporaire, c'est =$GUIX_ENVIRONMENT= qui pointe vers l'endroit approprié. Sans l'argument =-p $GUIX_ENVIRONMENT=, Guix afficherait autant les paquets dans mon profil permanent (le profil par défaut de mon compte) en plus des paquets qui font partie de mon environnement temporaire.

Ma petite liste ci-dessus contient seulement les paquets que j'ai installés explicitement. Chaque paquet dans cette liste a des dépendances, que Guix a rajoutées automatiquement. Leurs versions comptent tout autant, car elles peuvent influencer les résultats de mes calculs. Pour ne citer qu'un exemple, =python-statsmodels= dépend de =python-patsy=, qui fournit le cadre pour définir des modèles statistiques. Une erreur dans =python-patsy= peut donc fausser mes résultats. Il faudrait alors idéalement connaître les versions de toutes les dépendances, directes et indirectes.

À ma connaissance, Guix ne propose pas de commande pour récupérer cette liste. Je vais la récupérer par un petit script en langage Guile, le langage de Guix. Je vous le montre sans explications :
#+begin_src guile :exports both :tangle moocrr_guix_jupyter/installed-dependencies.scm :eval no
(use-modules (guix profiles)
             (gnu packages)
             (srfi srfi-1))

(define manifest
  (specifications->manifest
   '("jupyter"
     "python-matplotlib"
     "python-numpy"
     "python-pandas"
     "python-statsmodels"
     "python-nbconvert")))

(define (manifest-entry-name-and-version entry)
  (string-append (manifest-entry-name entry)
                 "@"
                 (manifest-entry-version entry)
                 "\n"))

(define transitive-entries
  (manifest-transitive-entries manifest))

(define transitive-packages
  (delete-duplicates
   (stable-sort
    (map manifest-entry-name-and-version transitive-entries)
    string<)))

(format #t "~a packages:\n" (length transitive-packages))
(format #t "~a"
 (apply string-append transitive-packages))
#+end_src

Et le résultat est...
#+begin_src sh :results output :exports both
guix repl moocrr_guix_jupyter/installed-dependencies.scm
#+end_src

Il faut donc 119 paquets au total pour construire mon environnement ! Et ce sont seulement les paquets qui doivent être en mémoire pour utiliser l'environnement. D'autres paquets ont été déployés pour construire ces 118 paquets. Par exemple, pour construire le paquet =python= il a fallu un compilateur C. Une erreur dans ce compilateur peut aussi fausser mes résultats, donc je devrais le rajouter à ma liste de paquets dont il faut noter les versions. Alors... encore un petit script pour faire la liste complète !

#+begin_src guile :exports both :tangle moocrr_guix_jupyter/all-dependencies.scm :eval no
(use-modules (guix profiles)
             (guix packages)
             (gnu packages)
             (srfi srfi-1))

(define manifest
  (specifications->manifest
   '("jupyter"
     "python-matplotlib"
     "python-numpy"
     "python-pandas"
     "python-statsmodels"
     "python-nbconvert")))

(define (manifest-entry->package entry)
  (car
   (find-packages-by-name
    (manifest-entry-name entry)
    (manifest-entry-version entry))))

(define (package->name-and-version entry)
  (string-append (package-name entry)
                 "@"
                 (package-version entry)
                 "\n"))

(define packages-in-manifest
  (map manifest-entry->package (manifest-entries manifest)))

(define closure-of-manifest
  (package-closure packages-in-manifest))

(define package-names-in-closure
  (stable-sort
   (delete-duplicates (map package->name-and-version closure-of-manifest))
   string<))

(format #t "~a packages:\n" (length package-names-in-closure))
(format #t "~a"
 (apply string-append package-names-in-closure))
#+end_src

Et le résultat est...
#+begin_src sh :results output :exports both
guix repl moocrr_guix_jupyter/all-dependencies.scm
#+end_src

** 2.6 Mettre son environnement à disposition
L'environnement étant défini par le manifeste, il suffit de mettre ce petit fichier à disposition de ses collègues pour leur permettre de travailler dans un environnement identique. Sauf que... les versions qu'ils auront ne sont peut-être pas les mêmes ! Peu après la publication d'une nouvelle version de Jupyter, Guix adoptera cette nouvelle version, et l'environnement créé par mon manifeste ne sera plus le même. Ceci est d'ailleurs voulu : souvent on veut tout juste avoir la dernière version de tout. Mais pour la reproductibilité, on veut tout à l'identique.

L'information qu'il faut rajouter, c'est la version de Guix à laquelle le manifeste fait référence. On l'obtient avec :
#+begin_src sh :results output :exports both
guix describe
#+end_src

Ceci me dit d'abord que je suis dans la génération 20 de Guix, ce qui veut dire que j'ai mis à jour Guix 19 fois depuis la première installation. Guix garde une trace de mes mises à jour et me permet de revenir en arrière si je le souhaite. Mais ce qui nous intéresse maintenant, c'est la suite. La version de Guix que j'utilise, c'est la =df931ac=. En tant qu'habitués de =Git=, vous devinez peut-être ce que c'est, et vous avez raison : c'est bien un commit, et vous le voyez dans sa totalité dans la dernière ligne. Guix est développé sous Git, et on peut donc identifier une version précise par son identifiant de commit. Les trois dernières lignes donnent un peu plus de précisions, dont notamment l'URL où on peut récupérer le dépôt.

** 2.7 Reconstruire un environnement
Maintenant je me place du côté du consommateur. J'ai reçu un notebook Jupyter accompagné d'un fichier =manifest.scm= et d'un commit. Que faire ?

La réponse est simple : je fais appel à la machine à voyager dans le temps. Pour lancer Jupyter dans un environnement "pur", la commande était bien :
#+begin_src sh :results output :exports both :eval no
guix environment --pure -m ./moocrr_guix_jupyter/manifest.scm -- jupyter notebook
#+end_src
Pour faire exactement la même chose plus tard, quand Guix aura avancé, je demande simplement à Guix de se placer sur le commit de sa version antérieure qui m'intéresse :
#+begin_src sh :session *time-machine* :results output :exports both
guix time-machine --commit=df931ac39c40ac8a702e37cb434d9a1016606ed7 -- environment --pure -m ./moocrr_guix_jupyter/manifest.scm -- jupyter notebook
#+end_src

Attention, la première fois que je lance =guix environment= après =guix pull=, il se peut que Guix se mette à compiler une bonne partie des 570 paquets listés ci-dessus. Mieux vaut prévoir du temps !

Avec =guix time-machine=, tout ce qui se passe après le premier =--= est passé à la commande =guix= dans sa version définie par le commit indiqué. On travaille donc à 100 % avec le Guix historique.

** 2.8 Mettre son environnement à disposition sous forme d'une image Docker
Il reste un problème que vous pouvez rencontrer : vos collègues n'utilisent pas Guix, peut-être même pas Linux. Un manifeste et un commit ne vont pas leur être utiles. En attendant qu'ils se mettent à utiliser Guix, vous pouvez leur fournir votre environnement sous forme d'une image Docker probablement plus simple à utiliser :
#+begin_src sh :results output :exports both
guix pack -f docker -m ./moocrr_guix_jupyter/manifest.scm
#+end_src

La commande nous affiche le nom du fichier qui contient l'image Docker. Il peut paraître un peu bizarre, tout comme le répertoire =/gnu/store= dans lequel le fichier se trouve. Quand on comprend le fonctionnement de Guix un peu mieux, tout ça s'explique facilement mais pour ce tutoriel, je vais me contenter de le copier ailleurs avec un nom plus parlant :

#+begin_src sh :results output :exports both
cp /gnu/store/hgd89l0r46liqwlz4idhwaymsngrm255-docker-pack.tar.gz moocrr-jupyter-docker.tar.gz
#+end_src

Sur une machine avec Docker installé, l'image est chargée avec :
#+begin_src sh :results output :exports both
docker load -i moocrr-jupyter-docker.tar.gz
#+end_src

puis Jupyter est exécuté avec :
#+begin_src sh :results output :exports both
docker run -it -p 8888:8888 jupyter-python-matplotlib-python-numpy:latest jupyter notebook --ip=127.0.0.1 --allow-root
#+end_src

** 2.9 Modifier son environnement
Je vous ai montré comment vous pouvez installer des logiciels avec Guix avec toutes leurs dépendances, et comment archiver et reconstruire un tel environnement. Ceci couvre une grande partie des opérations nécessaires pour pratiquer la recherche reproductible. Mais comment faire si vous voulez (ou devez) modifier un environnement donné, que ce soit le vôtre ou un environnement récupéré sous forme d'un manifeste ?

Commençons avec la situation la plus simple : vous voulez mettre à jour tous les logiciels à la dernière version. Pour cela un simple =guix pull= suffit :
#+begin_src sh :results output :exports both :eval no
guix pull
#+end_src
et la prochaine fois que vous faites :
#+begin_src sh :session *jupyter-env* :results output :exports both :eval no
guix environment -m ./moocrr_guix_jupyter/manifest.scm
#+end_src
vous utilisez les versions indiquées dans la toute dernière version de Guix. Mais que faire s'il vous faut une combinaison de versions qui ne se trouve nulle part dans l'historique de Guix ? Par exemple, pour chercher la cause d'un bug introduit récemment par un changement dans votre environnement, vous voulez combiner la dernière version de =python-statsmodels= avec une version plus ancienne de =python-pandas=.

Avant de passer à l'acte, il faut bien comprendre que ce genre de modifications est risqué. Rien ne promet que la combinaison de versions que vous envisagez est installable, et encore moins qu'elle fonctionne. Vous pouvez rencontrer un grand nombre de problèmes sur votre chemin, et c'est à vous de trouver une solution. Dans la vaste majorité des "petites" modifications, où on remplace une version relativement stable d'un logiciel par une version proche dans l'historique, la procédure que je vais montrer fonctionne sans difficulté, mais on n'est jamais à l'abri de mauvaises surprises !

Guix propose plusieurs façons d'introduire des modifications. Il n'est pas facile d'en choisir la meilleure sans avoir une certaine expérience de Guix. Je vous en montre une qui me paraît bien adaptée à la situation : définir un nouveau paquet, localement sur votre ordinateur, qui hérite de la plupart des caractéristiques d'un paquet existant. Comme exemple, je vais remplacer la version 1.0.5 de Pandas par la version 1.0.4.

Je commence en regardant la définition du paquet =python-pandas= dans Guix :
#+begin_src sh :results none :exports code
guix edit python-pandas
#+end_src
Ceci ouvre le fichier =python-science.scm= dans un éditeur de texte avec le curseur sur la définition de =python-pandas=. Il y a deux champs que je vais devoir remplacer : le numéro de version et la référence au code source. Tout le reste peut rester pareil - j'espère ! Voici le début de ma nouvelle définition :
#+begin_src guile :exports code :eval no
(package
 (inherit python-pandas)
 (version "1.0.4")
 (source
  (origin
   (method url-fetch)
   (uri (pypi-uri "pandas" version))
   (sha256
    (base32
     "09j13y1ydwb4pryazchicxw9zjm1031j49p5h8gbb9xsh9964pdk")))))
#+end_src
Comme annoncé, j'ai modifié la version. Et dans le champ =source=, j'ai changé la somme de contrôle =sha256= qui doit correspondre au fichier téléchargé pour la version 1.0.4. Pour trouver la bonne somme de contrôle, Guix m'a aidé :
#+begin_src sh :results output :exports both
guix download https://files.pythonhosted.org/packages/source/p/pandas/pandas-1.0.4.tar.gz
#+end_src

mais vous êtes libre de faire appel à toute technique à laquelle vous faites confiance. Le but est d'être sûr que vous récupérez le code source d'un serveur fiable !

Pour compléter la définition du paquet, qui est en fait du code en langage Guile (comme avant pour le manifeste), il faut importer quelques modules :
#+begin_src guile :exports both :tangle moocrr_guix_jupyter/pandas.scm  :eval no
(use-modules (guix packages)
             (guix download)
             (guix build-system python)
             (gnu packages python-science))

(package
 (inherit python-pandas)
 (version "1.0.4")
 (source
  (origin
   (method url-fetch)
   (uri (pypi-uri "pandas" version))
   (sha256
    (base32
     "09j13y1ydwb4pryazchicxw9zjm1031j49p5h8gbb9xsh9964pdk")))))
#+end_src
Comment savoir quels modules importer ? Le plus simple est =(gnu packages python-science)=, parce que c'est là qu'on a trouvé la définition de =python-pandas=. Sinon, il faut toujours =(guix packages)= et =(guix download)=. Pour finir, pour un paquet Python il faut toujours =(guix build-system python)=. Mais si vous oubliez un paquet, il y a une bonne chance que Guix vous indique le module manquant.

Pour compiler le paquet et exécuter sa batterie de tests, la commande est :
#+begin_src sh :results none :exports code
guix build -f moocrr_guix_jupyter/pandas.scm
#+end_src
Attention, c'est long, et ça produit plus de 60 000 lignes de texte diagnostic que je ne vais pas reproduire ici. Les deux dernières lignes sont :
#+begin_example
successfully built /gnu/store/dy0g3q6n07s7qz201ii2ib3iva9pmzp5-python-pandas-1.0.4.drv
/gnu/store/00xc4s45m68lhwl28mqd5l90pkjdxrf6-python-pandas-1.0.4
#+end_example
et la toute dernière indique le répertoire où se trouve le nouveau paquet. Reste la question de savoir comment l'intégrer dans mon environnement. La réponse n'est pas difficile sur le principe ("il faut modifier le manifeste"), mais les détails techniques sont un peu laborieux - une lecture du manuel de Guix s'impose. Voici le manifeste final :
#+begin_src guile :exports both :tangle moocrr_guix_jupyter/manifest-with-pandas-1.0.4.scm :eval no
(use-modules (guix packages)
             (guix download)
             (guix build-system python)
             (gnu packages python-science))

(define modified-python-pandas
  (package
   (inherit python-pandas)
   (version "1.0.4")
   (source
    (origin
     (method url-fetch)
     (uri (pypi-uri "pandas" version))
     (sha256
      (base32
       "09j13y1ydwb4pryazchicxw9zjm1031j49p5h8gbb9xsh9964pdk"))))))

(define standard-packages
  (map (compose list specification->package+output)
       '("jupyter"
         "python"
         "python-matplotlib"
         "python-numpy"
         "python-statsmodels"
         "python-nbconvert")))

(packages->manifest
 (cons modified-python-pandas
       standard-packages))
#+end_src


Et voici la preuve que ça marche - on demande à Python d'imprimer le numéro de version de Pandas :
#+begin_src sh :results output :exports both
guix environment --pure -m 
./moocrr_guix_jupyter/manifest-with-pandas-1.0.4.scm -- python3 -c 'import pandas; print(pandas.__version__)'
#+end_src

En fait, si vous comparez bien mon nouveau manifeste avec celui d'origine, vous remarquez que j'ai rajouté =python= qui n'y était pas avant. C'est juste pour pouvoir apporter cette preuve de réussite de l'opération !
