image: brospars/pandoc-gitlab-ci:latest
pages:
  stage: deploy
  script:
  - pandoc --version
  # - pandoc --help
  # - pandoc --list-input-formats    # Broken as pandoc dates from 2013 on this image! :(
  - for file in $(find -name "*.md") $(find -name "*.org"); do
        bin/pandoc_fixer.pl ${file};
        mkdir -p public/`dirname ${file}`
        mv ${file%.*}.html public/`dirname ${file}`;
    done
  - shopt -s extglob
  # - mv !(public) public
  artifacts:
    paths:
    - public
  only:
  - master
