# -*- mode: org -*-
#+TITLE: LaTeX
#+DATE: February 2020
#+STARTUP: overview indent
#+OPTIONS: num:nil toc:t
#+PROPERTY: header-args :eval never-export

LaTeX is a document typesetting language that is widely used to write scientific articles. We do not use LaTeX directly in this MOOC, but it is used by Jupyter, RStudio and Emacs/Orgmode to produce PDF output. LaTeX is a rather big piece of software (a complete installation takes one to five GB), so you may prefer not to install it. That will not prevent you from following the MOOC, you just lose the ability to produce PDF versions of your computational documents.

* Version requirements
LaTeX evolves rather slowly, so even a installation that is a few years old should be fine.

* Installation
There are many ways to install LaTeX. Worse, there are good reasons for there being many ways, because there is no single best one for everybody. The following guidelines should help you pick a good one for you.

** Linux
*Linux users* should start by checking the packages provided by their Linux distribution. It almost certainly contains LaTeX. The exact names of the package(s) you need to install unfortunately vary among distributions, but they should be similar to =texlive=.
** MacOS
We recommend one of two distributions that have stood the test of time: [[https://www.tug.org/mactex/][MacTeX]] or [[https://miktex.org/][MiKTeX]].
** Windows
We recommend one of two distributions that have stood the test of time: [[https://tug.org/texlive/][TeX Live]] or [[https://miktex.org/][MiKTeX]].
* On TinyTex

Yihui Xie, author of the great "bookdown" =R= package, has developed a "light LaTeX" version: TinyTex ("[[https://yihui.name/tinytex/][A lightweight, cross-platform, portable, and easy-to-maintain LaTeX distribution based on TeX Live]]").
