#+TITLE: Interview with Laurent Romary on TEI's interest in reproducible research
#+Date: <Mars 2020>
#+Author: Laurent Romary
#+LANGUAGE: fr
** Biography
   :PROPERTIES:
   :CUSTOM_ID: biography
   :END:

Laurent Romary is Director of Research within the ALMAnaCH team at
Inria. The focus of his research is computational linguistics and data
modelling at the interface between computer science and humanities. He
has participated in and coordinated standardisation initiatives for the
last 20 years as part of ISO technical committee 37
([[https://www.iso.org/committee/48104.html][International Organization
for Standardization]]) and the TEI consortium
([[https://tei-c.org/][Text Encoding Initiative]]).

** Interview
   :PROPERTIES:
   :CUSTOM_ID: interview
   :END:

*** How can the question of reproducibility be translated into the
humanities and human sciences?
    :PROPERTIES:
    :CUSTOM_ID: how-can-the-question-of-reproducibility-and-transparency-be-translated-into-the-humanities-and-human-sciences-much-is-said-about-the-difficulty-of-reproducing-statistical-results-from-experiments.
    :END:

In the humanities, research is primarily based upon the concept of
sources, corresponding to any human record that has been written, drawn
built...or destroyed, which is then analysed, either individually or as
part of a group, in order to develop a better understanding of what
characterizes us as humans. The problem of reproducibility can be summed
up as the ability of a researcher to *verify claims made by his or her
colleagues in relation to a set of sources used as the basis for an idea
or a theory*. Understanding an event such as the battle of Antioch[fn:1]
(28th June 1098), for example, requires corroborating sparse written
records (letters, chronicles, legislative acts, death registers), which
may contradict each other and which are preserved in very different
institutions scattered across the world. It can be very difficult for a
researcher to access the same sources as their predecessors and,
therefore, to arrive at the same conclusions.

*** What is a "result" and what is "robust" research in the humanities?
    :PROPERTIES:
    :CUSTOM_ID: what-is-a-result-and-what-is-robust-research-in-the-humanities
    :END:

Results come in many different forms - this could be the assertion of a
historic event, a causal link, the existence of a particular property in
a language or an influence on the creation of a work. **In all cases,
unlike in more experimental sciences, "results" in the humanities will
not be the fruit of an experiment that can be reproduced, but rather a
convergence of observations that other researchers will be able either
to confirm or disprove. This is what makes a result robust. Analysis of
a particular source may itself be a result when the aim is to understand
its context, its structure or its meaning. In this way, scientific
research in the humanities may concern the presentation of objects from
an archaeological dig, an old master or the transcription of a medieval
manuscript. In such a context, one aspect of scientific research
involves precisely defining ways of representing the object in question,
as shown by the work carried out by Andrew Dunning at the Bodleian
Library[fn:2], which proposes a specific framework for representing
medieval manuscripts.

*** Where does your research stand in relation to the issue of
reproducibility and transparency?
    :PROPERTIES:
    :CUSTOM_ID: where-does-your-research-stand-in-relation-to-the-issue-of-reproducibility-and-transparency
    :END:

The switch to digital sources and methods really shook up research in
the human sciences. It is now possible to bring together rare,
widely-scattered records into digital corpora that can easily be
accessed by other researchers. *Researchers can now verify assertions
made by their colleagues almost immediately, provided the source has
been translated into a digital form that is easily observable and
consultable*. Thanks to the research carried out as part of the /Letters
and Texts/[fn:3] project, researchers interested in discussions between
intellectuals in Berlin in the early 19th century can go and read their
correspondence online, without any restrictions. My research is focused
on defining data models, drawing in particular on the directives issued
by the TEI, the goal being to make it easy to compare such texts and to
boost the reproducibility of corresponding research.

*** How does the TEI boost transparency in research?
    :PROPERTIES:
    :CUSTOM_ID: how-does-the-tei-boost-transparency-in-research
    :END:

*The TEI is a vocabulary and a set of specifications* used to represent
text-based documents using the metalanguage XML defined by the W3C. By
defining structures adapted to different types of texts (plays,
manuscripts, correspondence, dictionaries), in addition to lighter
components (bibliographies, metadata, structures of records linked to
content), *the TEI has created a common language for researchers working
on digital sources, making it easier for them to share the results of
their research*. This enables them to encode etymological descriptions
following the same principles, or to compare their interpretations of a
complex passage from a Vindolanda[fn:4] tablet that they are looking to
decipher. The fruit of their research and the analysis drawn from it can
be shared transparently and read by other colleagues sharing *the same
conceptual framework*[fn:5].

*** What are the benefits of putting a text in TEI format as opposed to
epub format, for example?
    :PROPERTIES:
    :CUSTOM_ID: what-are-the-benefits-of-putting-a-text-in-tei-format-as-opposed-to-epub-format-for-example
    :END:

While the majority of languages used to represent text-based documents
place an emphasis on the visual appearance of the materials (if an
object is in bold, centred or in a certain font), *the TEI places an
emphasis on the semantics of the objects being represented*. Thus, it
will be indicated that a sequence in a text represents the name of a
person or a an expression of foreign origin, and not that it appears in
italics in the original document. In this way, when multiple researchers
share research carried out on different sources, it will be possible to
find all shared elements there, e.g. an individual appearing
transversally in different chronicles from the same era.

*** When is it beneficial to switch over to TEI?
    :PROPERTIES:
    :CUSTOM_ID: when-is-it-beneficial-to-switch-over-to-TEI-at-what-stage-of-research-should-I-switch-to-encoding-is-it-worth-the-effort-if-I-have-already-made-a-lot-of-progress-in-my-research-project
    :END:

Ideally, it is best to begin *encoding a document before you even really
observe it*. The TEI proposes a header for each document, which can
contain a whole host of information relating to where it came from, its
physical nature, etc. This header corresponding to the metadata linked
to the digitised object *can be continuously added to* in order to
include different pieces of information relating to the research project
in question, to how the content has been sampled or to the level of
annotation. It is also possible to outline the conditions for
distribution and reuse (e.g. licensing). In fact, the TEI enables the
gradual construction of a /digital surrogate/, where the transcription
or the annotation of a document is put in the context of its exact
description. In this way, we are able to confirm the authenticity of a
source and its transformation into a reusable digital object.

*** Is this not very complicated for novices? What IT skills are needed?
Do I need to know XML for example?
    :PROPERTIES:
    :CUSTOM_ID: is-this-not-very-complicated-for-novices-what-it-skills-are-needed-do-I-need-to-know-xml-for-example-what-are-the-prerequisites
    :END:

The TEI is based on the metalanguage XML, but it does not take long to
grasp the basics, as I discovered during the many orientation sessions I
attended. Although based on a vocabulary of nearly 600 elements and many
different attributes, *it takes no time at all to represent a simple
text, or even a dictionary, using a vocabulary of around fifteen or so
elements*. Guidance is essential when starting out, either through a
training course or from a more advanced colleague, in order for the
logic associated with the elements used and where they overlap to be
understood straight away. *No prior knowledge of advanced computing or
programming is necessary. You just need to know how to use a text editor
and a certain amount of common sense*.

*** How can the quality of the encoding be ensured? What is considered
best practice, particularly when working as part of a group?
    :PROPERTIES:
    :CUSTOM_ID: how-can-the-quality-of-the-encoding-be-ensured-what-is-considered-best-practice-particularly-when-working-as-part-of-a-group
    :END:

With regard to the syntax of encoding, i.e. which elements to use and
where, the TEI has defined an XML blueprint. *XML editing tools use such
a blueprint, not just /to validate/ the encoding (this is the technical
term), but also to guide the encoder in the choices available to them as
they work*. In order to judge the quality of the representation, we rely
on the online documentation, which contains a coherent and detailed
description of the elements available for such and such a type of
document (e.g. the transcription of oral data[fn:6]), and for each
element you can access its precise documentation, which will give its
conditions for use (e.g. the encoding of sound pauses in a
conversation[fn:7]).

When working as part of a group, particularly on a specific research
project, it is important *to reach an agreement on standard practices*,
e.g. in terms of how detailed the coding is or the use of specific
elements to annotate crucial components for the research in question.
Ideally, the members of a collaborative project will keep a *coding
manual*, which will be updated regularly during coordination meetings.
*Cross-verification procedures between colleagues* are used to verify
that the sources being studied have been understood in the same way. *In
the end, this concept of common understanding is why the TEI directives
are often seen as the expression of a shared culture*.

*** Are these encoding techniques only relevant when data is being
shared or are they also useful when I'm working on my own?
    :PROPERTIES:
    :CUSTOM_ID: are-these-encoding-techniques-only-relevant-when-data-is-being-shared-or-are-they-also-useful-when-im-working-on-my-own
    :END:

It is the same as in any other discipline - *you have to think first and
foremost about reproducibility for yourself*. It is essential to be able
to return to a data set that has been created or a document that has
been encoded after a period of time and still be able to understand the
findings and make new observations. You share data with yourself before
sharing it with other people. *This is particularly important in the
human sciences, where researchers will accumulate observations over
time* linked to the era, the location or the exact phenomenon
(e.g. conflicts, migrations, religious fact) *corresponding to their
particular theme or themes. The TEI thus makes it possible to build a
stable digital heritage over time*.

*** From a practical point of view, what do I need to do TEI? What
technical solutions are required?
    :PROPERTIES:
    :CUSTOM_ID: from-a-practical-point-of-view-what-do-i-need-to-do-tei-what-technical-solutions-are-required
    :END:

To begin with, all you need is a relatively user-friendly *XML editor*,
such as Oxygen (proprietary software, but the Rolls Royce in its field),
to which is added the TEI directives blueprint (or a customisation of
it). Once you have started working on a few documents, it can be useful
to learn how to *handle them using a language such as XSLT*, which can
be used to quickly produce a browser-readable HTML version, which can be
practical for giving a general overview, while also enabling you to show
your results to your colleagues. Eventually, as is the case for any
dataset, thought must be given to *a hosting environment*, enabling you
to share documents. Depending on the available resources, documents can
be shared on a generic server such [[https://www.ortolang.fr/][as
Ortolang]] or [[https://www.nakala.fr/][Nakala]], an environment
dedicated to the TEI such as [[https://tapasproject.org/][TAPAS]], or
you can develop your own sharing platform.

*** Could you give us an example of a research question that the TEI
helped bring about?
    :PROPERTIES:
    :CUSTOM_ID: could-you-give-us-an-example-of-a-research-question-that-the-tei-helped-bring-about-show-that-the-tei-goes-further-than-markup-that-it-is-useful-for-exploratory-analysis-for-example.
    :END:

*When you have a complex set of sources with content that is difficult
to analyse by hand, systematic coding will very quickly reveal trends or
correlations that simple tools can highlight*. In the context of the
project in Cologne aimed at establishing a Classic Mayan dictionary and
textbase, researchers were thus able to greatly increase their capacity
to find new interpretations of the written Mayan language, which has
only been partially deciphered[fn:8]. What makes this project
particularly interesting is that it combines textual representation in
TEI with images, meaning that literally each glyph is associated with an
observable (these tend to be epigraphic, with the Spanish colonisers
having destroyed much of the Mayans' handwritten heritage).

*** How do you use the TEI?
    :PROPERTIES:
    :CUSTOM_ID: how-do-you-use-the-tei
    :END:

My research is focused on *defining standardised structures associated
with different types of documents in the human sciences*. As a result, I
am in constant dialogue with researchers, trying to understand their
representation objectives and to identify the best possible encoding,
which will enable them to be faithful to both the source text and the
researcher's own analysis. For me, the TEI is a modelling tool, and one
that is constantly available - I receive a great number of messages from
colleagues asking me for advice for the detailed representations they're
working on. In doing so, I am regularly confronted with objects which
resist the TEI, because there is a descriptive element missing, or a
construction which had not been anticipated. It is then that we have to
contribute to the standardisation process by evolving the TEI
directives. With two versions published each year and an online space on
GitHub where each evolution proposal is discussed in concert with the
TEI's technical committee, the TEI is a shining example of an open,
inclusive standardisation space.

*** Where is the TEI headed?
    :PROPERTIES:
    :CUSTOM_ID: where-is-the-tei-headed
    :END:

The TEI has become *the leading reference* for all projects involving
the digital editing of sources in the human sciences, so much so that it
has even been recommended by different funding organisations, including
the DFG in Germany[fn:9]. There remains much to be done in order to
improve the distribution of solid digital culture in the human sciences,
including the introduction of methodological courses at Master's level,
which will be brought in very soon. What's more, the TEI directives
still have to be improved in order to cover more disciplines and to
offer precise, targeted sub-assemblies for ever more varied document
types, such as Tweets or exchanges in online forums, for example, which
are now the subject of linguistic and sociological studies.

[fn:1] Florian Besson, "Croiser les littératures de la première
       croisade : l'exemple de la bataille d'Antioche", /in/ M. Finck,
       T. Victoroff, E. Zanin, P. Dethurens, G. Ducrey, Y.-M. Ergal, P.
       Werly (éd.), /Littérature et expériences croisées de la guerre,
       apports comparatistes. Actes du XXXIX^{e} Congrès de la SFLGC/,
       URL: [[http://sflgc.org/acte/florian-besson-croiser-les-litteratures-de-la-premiere-croisade-lexemple-de-la-bataille-dantioche/][<http://sflgc.org/acte/florian-besson-croiser-les-litteratures-de-la-premiere-croisade-lexemple-de-la-bataille-dantioche/>]],
       page viewed on 10th February 2020

[fn:2] [[https://andrewdunning.ca/transcribing-medieval-manuscripts-tei]]

[fn:3] [[https://www.berliner-intellektuelle.eu][<https://www.berliner-intellektuelle.eu>]]

[fn:4] [[http://vindolanda.csad.ox.ac.uk][<http://vindolanda.csad.ox.ac.uk>]]

[fn:5] Terras, M. & Robertson, P. (2004). Downs and acrosses: textual
       markup on a stroke level. /Literary and linguistic computing/,
       /19/ (3), 397-414. [[https://doi.org/10.1093/llc/19.3.397]]

[fn:6] [[https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/TS.html][<https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/TS.html>]]

[fn:7] [[https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-pause.html][<https://www.tei-c.org/release/doc/tei-p5-doc/fr/html/ref-pause.html>]]

[fn:8] [[https://mayawoerterbuch.de/a-new-logogram-for-hul-to-arrive-implications-for-the-decipherment-of-the-month-name-cumku/]]

[fn:9] [[https://www.dfg.de/formulare/12_151/12_151_en.pdf][https://www.dfg.de/formulare/12\\_151/12\\_151\\_en.pdf]]

