# -*- ispell-local-dictionary: "american" -*-
#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: Additional Ressources for Module 1
#+DATE: <2019-02-22 ven.>
#+AUTHOR: Christophe Pouzat
#+EMAIL: christophe.pouzat@parisdescartes.fr
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.9)
#+STARTUP: indent

* Sequence 1

This sequence discusses a much wider issue than /reproducible research/ (RR). Implementing RR requires thorough note-taking and note-taking concerns everyone. The purpose of this sequence is therefore to remind the reader / auditor that he/she already knows: *note-taking concerns everyone*. Few examples are used to that end. 

** Annotated manuscripts
As an introduction to the world of annotated manuscripts, I quote now a small selection of passages from the first chapter of /LA PAGE. DE L'ANTIQUITÉ À L'ÈRE DU NUMÉRIQUE/ (THE PAGE. FROM ANTIQUITY TO THE DIGITAL ERA) by Anthony Grafton (Hazan, 2012):

#+BEGIN_EXAMPLE
  By the very movement of his pen on the page, it is clear that
Casaubon masters everything he reads. He constantly underlines the importance of
words and expressions, he notes in the margin key words and summaries
showing that he has read carefully, even when, he states in his
diary that he studied in one day forty to fifty pages
in-folio of Greek with many abbreviations. The most important 
passages give rise to longer comments in the margin.
On the title pages, Casaubon very often carries - a little
as Montaigne - a global judgment on the value of the work.
In addition, he notes his thoughts in notebooks, or takes
notes on texts he can't buy. As they are
gathered in his library, his books represent a whole life of
reading that can be reconstructed over the pages.
#+END_EXAMPLE

Pages 32 and 33, about [[https://en.wikipedia.org/wiki/Isaac_Casaubon][Isaac Casaubon]] (1559-1614).

#+BEGIN_EXAMPLE
  Yet Harvey left much more than that, including
traces of his readings in the form of more than a hundred books
covered with wonderfully written annotations of his beautiful slanted 
writing - in addition to the notebooks in which he wrote extracts.
Clearly, Harvey considered reading to be his profession,
and he made it an art too. Decade after decade, he lays down his
thoughts on history in an in-folio edition of 1555 of Livy's "History
of Rome". His notes, mostly in Latin, go through
the margins, spread between chapters and fill in
loose sheets, taking on a particularly erudite aspect and
quite daunting.
#+END_EXAMPLE

Pages 35 and 36, on [[https://en.wikipedia.org/wiki/Gabriel_Harvey][Gabriel Harvey]] (1545-1630).

#+BEGIN_EXAMPLE
... But in the remaining working copy of the
text, the basic edition of 1549, he [Casaubon] introduced so many annotations
that the cataloguers of the Bodleian Library, who were only
not familiar with rhetoric, have classified this printed book as a manuscript.
#+END_EXAMPLE

Page 40.

** Note cabinets from Placcius and Leibniz

I found this example in Ann Blair's work such as [[https://dash.harvard.edu/bitstream/handle/1/4774908/blair_notetaking.pdf?sequence=1][The Rise of Note-Taking in Early Modern Europe]] and her book /TOO MUCH TO KNOW. Managing Scholarly Information before the Modern Age/, published by Yale University Press in 2011.

** On the preface to /Penguin Island/

The text can be found /legally/ at several places, the [[https://en.wikipedia.org/wiki/Project_Gutenberg][Project Gutenberg]] one is missing the "Preface", so don't use it, go to one of the versions available on [[https://archive.org/search.php?query=title%3Apenguin%20island%20AND%20-contributor%3Agutenberg%20AND%20mediatype%3Atexts][Internet Archive]]. The importance of the preface in illustrated by the following two quotations:

#+BEGIN_QUOTE
One word more if you want your book to be well 
received, lose no opportunity for exalting the virtues on 
which society is based — attachment to wealth, pious senti- 
ments, and especially resignation on the part of the poor, 
which latter is the very foundation of order. Proclaim, sir, 
that the origins of property — nobility and police — are treat- 
ed in your history with the respect which these institutions 
deserve. Make it known that you admit the supernatural 
when it presents itself. On these conditions you will succeed 
in good society.
#+END_QUOTE

And more importantly for our present subject:

#+BEGIN_QUOTE
The idea occurred to me, in the month of June last year, to 
go and consult on the origins and progress of Penguin art, 
the lamented M. Fulgence Tapir, the learned author of the 
‘Universal Annals of Painting, Sculpture and Architecture’ 

Having been shown into his study, I found seated before a 
roll-top desk, beneath a frightful mass of papers, an amaz- 
ingly short-sighted little man whose eyelids blinked behind 
his gold-mounted spectacles. 

To make up for the defect of his eyes his long and mobile 
nose, endowed with an exquisite sense of touch, explored the 
sensible world. By means of this organ Fulgence Tapir put 
himself in contact with art and beauty. It is observed that in 
France, as a general rule, musical critics are deaf and art 
critics are blind. This allows them the collectedness neces- 
sary for æsthetic ideas. Do you imagine that with eyes capable 
of perceiving the forms and colours with which mysterious 
nature envelops herself, Fulgence Tapir would have raised 
himself, on a mountain of printed and manuscript docu- 
ments, to the summit of doctrinal spiritualism, or that he
would have conceived that mighty theory which makes the 
arts of all tunes and countries converge towards the Institute 
of France, their supreme end? 

The walls of the study, the floor, and even the ceiling were 
loaded with overflowing bundles, pasteboard boxes swollen 
beyond measure, boxes in which were compressed an in- 
numerable multitude of small cards covered with writing. I 
beheld in admiration minted with terror the cataracts of 
erudition that threatened to burst forth. 

‘Master,’ said I in feeling tones, ‘I throw myself upon 
your kindness and your knowledge, both of which are 
inexhaustible. Would you consent to guide me in my 
arduous researches into the origins of Penguin art?’ 

‘Sir,’ answered the Master, ‘I possess all art, you under- 
stand me, all art, on cards classed alphabetically and in 
order of subjects. I consider it my duty to place at your dis- 
posal all that relates to the Penguins. Get on that ladder and 
take out that box you see above. You will find in it every- 
thing you require.’ 

I tremblingly obeyed. But scarcely had I opened the fatal 
box than some blue cards escaped from it, and slipping 
through my fingers, began to rain down. Almost immediate- 
ly, acting in sympathy, the neighbouring boxes opened, and 
there flowed streams of pink, green, and white cards, and by 
degrees, from all the boxes, differently coloured cards were 
poured out murmuring like a waterfall on a mountain side 
in April. In a minute they covered the floor with a thick 
layer of paper. Issuing from their inexhaustible reservoirs 
with a roar that continually grew in force, each second in- 
creased the vehemence of their torrential fall. Swamped up 
to the knees in cards, Fulgence Tapir observed the cataclysm 
with attentive nose. He recognised its cause and grew pale 
with fright 

‘What a mass of art !’ he exclaimed. 

I called to him and leaned forward to help him mount the 
ladder which bent under the shower. It was too late. Over- 
whelmed, desperate, pitiable, his velvet smoking-cap and his 
gold-mounted spectacles having fallen from him, he vainly 
opposed his short arms to the flood which had now mounted 
to his arm-pits. Suddenly a terrible spurt of cards arose and 
enveloped him in a gigantic whirlpool. During the space of a 
second I could see in the gulf the shining skull and little fat 
hands of the scholar, then it closed up and the deluge kept 
on pouring over what was silence and immobility. In dread 
lest I in my turn should be swallowed up ladder and all I 
maae my escape through the topmost pane of the window.  
#+END_QUOTE

** The logbooks

I would like to thank Joël Caselli for helping me interpret the content of Éric Tabarly's logbook.

This example is only superficially anecdotal. Ten years ago, a European project was aiming at estimating the Atlantic and Indian Oceans climates during the 18th century using logbooks from ships of the West- and East-India companies from the Kingdoms of Portugal, Spain, Holland, Britain and France. See the [[http://webs.ucm.es/info/cliwoc/][Climatological Database for the World's Oceans 1750-1850]].
   
In the same vein, logbooks from slave ships give a lot of quantitative information about the slave trade between Africa and the "New World" (see Marcus Rediker frightening book /The Slave Ship: A Human History/, 2007).

** One missing: the classic laboratory notebook

I quote here Sec. 6.2 =Notebooks and Records= of the highly recommended reading /An Introduction to Scientific Research/ by E. Bright Wilson (reprinted by Dover):

#+BEGIN_QUOTE
It is hard to conceive of a perfect laboratory notebook, and it is regrettably rare to find one that is even moderately 
satisfactory; yet the keeping of good records of work done is a major key to efficiency. There are bound to be dissenters 
to any set of fixed rules, but these will probably be rarer for the ritual of notebook keeping than elsewhere. Consequently, 
a set of rules which is generally regarded as satisfactory, or even as essential, will be somewhat dogmatically stated.

Some great discoveries have been delayed because of careless record keeping. Thus it is related that the astronomer Le Monnier 
observed the planet Uranus on several occasions, before its identification as a planet had been announced by Herschel, but 
decided that it was a fixed star. This was probably due in part to the fact that he wrote his measurements on scraps of paper, 
including a paper bag originally containing hair powder!

Laboratory notebooks should be permanently and strongly bound and of sufficient size, say roughly 8 by 10 inches, with numbered 
pages. Loose-leaf pages or separate sheets are too easily lost to be satisfactory, especially since a laboratory notebook gets 
rather rough handling, and perhaps an occasional dousing with acid. An exception is the case of routine, repeated measurements, 
where a printed or mimeographed special blank is often useful if a good system is established for collecting and binding the 
separate sheets. Ruled pages are generally used, but this is a matter of personal taste, and some prefer unruled or cross-sectional 
pages. A rubber stamp may be used to provide headings for routine entries.

Data should be entered directly into the notebook at the time of observation. It is intolerable to use memory or scraps of paper 
for primary recording, because of the inevitability of error and loss. Therefore, there should be a good place for the notebook 
at the operating position, and the experimenter should never be without his book when in action.
Data should be recorded in ink, preferably a permanent brand, and a blotter should be handy. Otherwise the record is too ephemeral. 
Notebooks get hard usage, and pencil smudges rapidly. When the notebook may be used as evidence in a patent case, ink is much 
preferred. 

Rough, qualitative graphs can be drawn in directly, but more careful ones are usually best prepared on graph paper of the most 
appropriate type These are then carefully pasted in the notebook, a blank page being cut out in order to compensate for the bulk of 
the one added.

Notebooks should carry the name of the user and the dates covered. It is convenient in a research group to agree on a standard size, 
but then some sort of external identification is a great timesaver. The first eight or ten pages should be reserved for a table of 
contents. This consists of a line added chronologically for each series of similar experiments, together with the page reference. 
The table of contents is enormously helpful in finding items later and is very simple to keep up. An index in the back of the book 
is advantageous but not indispensable.

Each entry should be dated and, if several individuals use one book (not generally recommended), initialed. The material should not 
be crowded on the pages; paper is cheap compared with other research expenses. The principal difficulty is in deciding what to put in. 
Obviously, one enters numerical results and those values of the independent variables such as temperature, composition, or pressure 
which are directly concerned. It is also necessary to have a system of entries or references so that years later it will be possible to 
tell what apparatus was used and under what circumstances. Somewhere there should be available a rather complete description of the 
apparatus. Then, when modifications are made, they should be described immediately in the notebook. It should also be possible to trace 
back the source of calibration curves, corrections, etc., which were appropriate to the data of a given day. It is helpful if the 
requirements for writing a paper, a thesis, or a book are kept in mind. Such a task, once carried out, usually leads to solemn resolves 
to keep a more careful notebook in the future. Also extremely salutary is the effect of trying to figure out something from another’s 
book. All references to apparatus, places, times, books, papers, graphs, and people should be sufficiently explicit to be understandable 
years later. It should be possible to take each scientific paper and show just where every figure, description, or statement in it is 
backed up by original observations in the laboratory notebook, and exactly why the final and original numbers differ, if they do.

Some statement of the purpose of each experiment and a summary of the conclusions reached make the notebook vastly more useful.
Sketches, drawings, and diagrams are essential. Since so much observation is visual, it is important to record what is actually seen, 
including things not fully understood at the time. Bad or unpromising experiments, even those deemed failures, should be fully recorded. 
They represent an investment of effort which should not be thrown away, because often something can be salvaged, even if it is only a 
knowledge of what not to do. Data should always be entered in their most primary form, not after recalculation or transformation. If it 
is a ratio of two observations which is of interest but it is the two numbers which are actually observed, the two numbers should be 
recorded. If the precise weight of an object is important, the individual balance weights used and their identification should be 
included, i.e., the serial number of the box. Otherwise it is not possible to apply calibration corrections later or to change the 
corrections if new values appear. Naturally, this detail is not necessary if only a rough weight is involved. A tabular form is best for 
numerical data. Units should be noted.

Where patent questions are involved, it may be desirable to witness and even to notarize notebook pages at intervals. The witness should 
be someone who understands the material but is not a coinventor. Material added to a page at a later date should be in a different-colored 
ink, and any alterations should be initialed, witnessed, and dated if they are likely to be important. Industrial concerns usually enforce 
their own rules concerning patent matters.

Identification Numbers. It is foolish to spend time and money making records of various kinds such as pen-and-ink recorder sheets, 
photographic records, or spectra if these are then lost or mixed up. Every such record should carry indelibly on it complete identification. 
A simple system of doing this which has worked well in practice is to write in ink on each record a symbol identifying the notebook and then 
the page number on which the auxiliary data are recorded. If more than one record occurs on a page, letters or further numerals can be added. 
Thus EBW II 85c would identify the third record discussed on page 85 of the second EBW notebook. This is better than a serial number, which 
doesn’t tell without extra keying where to look for the notebook entry.
A good filing system is indispensable for all films, photographs, charts, graphs, circuit diagrams, drawings, blueprints, etc. It is hardest 
to devise satisfactory filing methods for either very small or very large material. The former are easily lost and the latter very bulky. 
Small envelopes are useful for tiny films and also protect them from scratching.

It is thoroughly worth while to save drawings and blueprints from which apparatus has been built, however rough these may be. These should be 
dated, initialed, and labeled; in fact every piece of paper containing useful material should be so marked. When an electronic or other 
similar piece of equipment is built, a careful circuit diagram should be prepared, fully labeled with all constants. The apparatus should 
carry a serial number which also appears on the diagram. When changes are made, these should be indicated on the diagram and dated or a revised, 
dated diagram made. The old one should not be obscured or thrown away because it may be required to explain earlier data, later found to be 
peculiar. It is convenient to draw such diagrams on tracing paper with a good black pencil. Cheap ozalid or similarly processed copies can then 
be made. One should be kept in the laboratory, where it will usually prove indispensable for trouble shooting. Sooner or later, however, it will 
be used as scratch paper by someone with a brilliant idea to demonstrate; so the official copy and spares should be filed elsewhere. A great deal 
of time is unnecessarily wasted poking around the insides of an apparatus trying to find out where some wire goes.
[...]
Labeling. Related to the question of notebooks and records is that of labeling. Naturally bottles of chemicals must carry adequate labels, which 
should include not only the chemical name but also the source, or a notebook page reference if there has been any special treatment, or initials 
and date. One research worker departed from a certain laboratory to take another job and left a good deal of material behind. One bottle of clear 
liquid carried no label. Those assigned to clean up examined it, smelled it, finally concluded that it was water, and poured it down the drain. 
It was water, all right—heavy water at $30 an ounce. Some supervisors relentlessly throw out unlabeled bottles on sight. It only needs to be done 
once or twice. Labels are also essential on all kinds of specimens, pieces of apparatus, gadgets, etc. Controls on apparatus should be labeled and 
the apparatus itself numbered. Every laboratory has orphaned pieces of equipment, often electronic, of which no one knows the nature and purpose. 
The notebook page system is good here, provided the old notebooks can be found. Labels should be attached so that they will stay. Metal tags can 
be riveted on. Paper labels should be covered with some sort of varnish.

The whole purpose of all these recording systems is to preserve values. They should be carefully thought out to fit the conditions of each 
laboratory and should be adequate but not overelaborate. If too much is demanded of human nature, the system will break down.
#+END_QUOTE 

* Sequence 2

** Illustrations used in the first figure

All illustrations are taken from Wikimedia Commons
- Top left: A clay tablet (pre-cuneiform period, -3000).
- Top center: A fresco from Pompeii with the portrait of [[https://en.wikipedia.org/wiki/Portrait_of_Paquius_Proculo][Terentius Neo and his wife]]. She carries a [[https://en.wikipedia.org/wiki/Wax_tablet][wax tablet]] and a /stylus/ (the main medium of note-takers up to the 19th century); he carries a /volumen/ or [[https://en.wikipedia.org/wiki/History_of_scrolls][scroll]], the stuff of books until the beginning of the Common Era.
- Top right: a notebook made of paper from the 17th century with [[https://en.wikipedia.org/wiki/Commonplace_book][commonplaces]]. "Commonplace" is a translation of the Latin term locus communis (from Greek tópos koinós, see literary topos) which means "a theme or argument of general application", such as a statement of proverbial wisdom (Wikipedia).
- Bottom left: An [[https://en.wikipedia.org/wiki/Index_card][index card]], a notes medium whose use exploded with bureaucratization and the development of libraries. Still heavily used in the humanities. Apparently first used (if not created) by the father of taxonomy, [[https://en.wikipedia.org/wiki/Carl_Linnaeus][Carl Linneaus]]. You can find his cards at: [[http://linnean-online.org/61332/#/0]].
- Bottom center: A [[https://en.wikipedia.org/wiki/Post-it_note][Post-it note]] as most of us use every day.
- Bottom right: A "modern days" numerical tablet.    

** Wax tablet and stylus

From the [[https://en.wikipedia.org/wiki/Wax_tablet][Wikipedia page]]:

#+BEGIN_QUOTE
A wax tablet is a tablet made of wood and covered with a layer of wax, often linked loosely to a cover tablet, as a "double-leaved" diptych. 
It was used as a reusable and portable writing surface in Antiquity and throughout the Middle Ages.

Writing on the wax surface was performed with a pointed instrument, a stylus. Writing by engraving in wax required the application of much 
more pressure and traction than would be necessary with ink on parchment or papyrus,[1] and the scribe had to lift the stylus in order to 
change the direction of the stroke. Therefore, the stylus could not be applied with the same degree of dexterity as a pen. A straight-edged, 
spatula-like implement (often placed on the opposite end of the stylus tip) would be used in a razor-like fashion to serve as an eraser. 
The entire tablet could be erased for reuse by warming it to about 50 °C and smoothing the softened wax surface. The modern expression of 
"a clean slate" equates to the Latin expression "tabula rasa".
#+END_QUOTE 

** From the /scroll/ to the /codex/

The shift from the /scroll/ to the /codex/ is fundamental for development of written civilization.

A scroll (from the Old French escroe or escroue), is a roll of papyrus, [[https://en.wikipedia.org/wiki/Parchment][parchment]], or paper containing writing.

From [[https://en.wikipedia.org/wiki/History_of_scrolls#Replacement_by_the_Codex][Wikipedia]]:

#+BEGIN_QUOTE
The codex was a new format for reading the written word, consisting of individual pages loosely attached to each other at one 
side and bound with boards or cloth. It came to replace the scroll thanks to several problems that limited the scroll's function 
and readability. For one, scrolls were very long, sometimes as long as ten meters. This made them hard to hold open and read, a 
difficulty not helped by the fact that most scrolls in that era were read horizontally, instead of vertically as scrolling virtual 
documents are read now. The text on a scroll was continuous, without page breaks, which made indexing and bookmarking impossible. 
Conversely, the codex was easier to hold open, separate pages made it possible to index sections and mark a page, and the protective 
covers kept the fragile pages intact better than scrolls generally stayed. This last made it particularly attractive for important 
religious texts.
#+END_QUOTE

The bottom left mosaic shows Virgil seating (70-19 BCE) holding a scroll of the /Aeneid/, with Clio, muse of history, also holding a scroll.

As explained by Frédéric Barbier (/Histoire du Livre/): "The scroll / volumen imposes a complex reading practice: one must unroll (/explicare/) and roll at the same time; that forbids working on several scrolls (the original text and its commentary) at the same time or to take notes. It imposes a continuous reading and making consultation impossible."

Scrolls are clearly unsuited to "nomadic reading"; can you imagine Ulysses embarking for his Odyssey carrying the 24 scrolls/volumen of the Iliad?

The term /volumen/ is the origin of our modern /volumes/ (a book in several volumes) as of the word for the geometrical concept.

Switching from scroll to codices required two innovations:
- The collection of wax tablets bound together with leather strands.
- The generalization of [[https://en.wikipedia.org/wiki/Parchment][parchment]] (usually sheep skin specially processed) as a replacement for [[https://en.wikipedia.org/wiki/Papyrus][papyrus]]. This generalization could be due (according to Pliny the Elder) to a rivalry between the cities of Pergamon and Alexandria for cultural hegemony: [[https://en.wikipedia.org/wiki/Ptolemy_V_Epiphanes][Ptolemy V Epiphanes]] King of Egypt wanted to block [[https://en.wikipedia.org/wiki/Eumenes_II][Eumenes II]] from developing in Pergamon a library that could compete with the one of Alexandria; he therefore imposed an embargo on papyrus export (Egypt was the sole papyrus producer). Eumenes looked for an alternative and fostered parchment development. The link between Pergamon and parchment is much clearer in German where Pergamon is written in the way as in English but where parchment is written /Pergament/.

Switching from scrolls to codices will have major consequences on books organization as well as on the reading practices, it will later on allow printing development.

The main revolution brought by the codex is the /page/. Thanks to this structural element, the reader can access directly to a specific chapter or a specific part of the text, while scrolls imposed continuous reading *at a time when there were no blanks between words*. According to Collette Sirat: "Twenty centuries will be necessary to realize the paramount importance of the codex for our civilization through the *selective reading* it made possible as opposed to the continuous reading. It opened room for the elaboration of mental structures where the text is dissociated from the speech and its rhythm."

Notice the red letters used on the codex (bottom right), an example of [[https://en.wikipedia.org/wiki/Rubrication][rubrication]] used by scribes to mark paragraphs. With printing and the high cost of colors it entailed, an empty space started to be used to that end. Thinking about it, colors don't cost anything on a numerical support and could perfectly be used again in the same way.  

** Eusebius and the invention of cross-references

From the Wikipedia page on [[https://en.wikipedia.org/wiki/Eusebius][Eusebius]]:
#+BEGIN_QUOTE
Eusebius of Caesarea (ad 260/265 – 339/340), also known as Eusebius Pamphili, was a historian of Christianity, exegete, and Christian polemicist. He became the bishop of Caesarea Maritima about 314 AD. Together with Pamphilus, he was a scholar of the Biblical canon and is regarded as an extremely learned Christian of his time. He wrote Demonstrations of the Gospel, Preparations for the Gospel, and On Discrepancies between the Gospels, studies of the Biblical text.
#+END_QUOTE

According to Anthony Grafton and Megan Williams (2006) /Christianity and the Transformation of the Book/, The Belknap Press of Harvard University Press, his writings are crucial for our knowledge of the first three centuries of Christian history. /He brought several essential innovations to the book's organization like the cross-references/.

** Eusebian canons

Quote from [[https://en.wikipedia.org/wiki/Eusebius#Biblical_text_criticism][Wikipedia]]:
#+BEGIN_QUOTE
For an easier survey of the material of the four Evangelists, Eusebius divided his edition of the New Testament into paragraphs and provided it with a synoptical table so that it might be easier to find the pericopes that belong together. These canon tables or "Eusebian canons" remained in use throughout the Middle Ages, and illuminated manuscript versions are important for the study of early medieval art, as they are the most elaborately decorated pages of many Gospel books.
#+END_QUOTE

** /Codex/ significance

Following Frédéric Barbier (/HISTOIRE DU LIVRE/, Armand Colin, 2009):
- /Codex/ invention is crucial for the development of written civilization.
- The /codex/ lends itself to *consultation reading*.
- We can add to the /codex/ a "navigation system" making consultation easier.
- We can take notes while consulting a /codex/.
- The combination of the /codex/ with the /Carolingian minuscule/ constitutes an extremely powerful intellectual tools, never seen before.

Example of /Carolingian minuscule/ can be found on the corresponding [[https://en.wikipedia.org/wiki/Carolingian_minuscule][Wikipedia page]].

Over centuries, /codices/---that we often call /manuscripts/---will slowly evolve and gain modern days book attributes:
- separation between words (VIIth century),
- start of punctuation (VIIIth century),
- table of content,
- running title,
- paragraph marks (rubrication, XIth century),
- pagination,
- index (XIIIth century).

An interesting point: Torah's content got "fixed" before the /codex/ generalization and today Torah scrolls are still used.  

** Let us not forget China

The link between the /codex/ generalization, on the one hand, and the apparition of "navigation guides" like the table of content, the index, the running title, on the other hand as a counterpart in the Chinese civilization.

In China, competitive examinations to become a high ranking state employee developed in the IXth century (CE). The main part of these exam was a paper on what we would now call general knowledge of the Classics where the students were asked to demonstrate their knowledge through appropriate quotations.

To fulfill the need of "textbook" appropriate for this kind of examination what is called [[https://en.wikipedia.org/wiki/Leishu][leishus]] were produced. They are described as follows on Wikipedia: 
#+BEGIN_QUOTE
The leishu are composed of sometimes lengthy citations from other works and often contain copies of entire works, not just excerpts. The works are classified by a systematic set of categories, which are further divided into subcategories. Leishu may be considered anthologies, but are encyclopedic in the sense that they may comprise the entire realm of knowledge at the time of compilation.
#+END_QUOTE   

The efficient use of the leishu requires an indexing system, a table of content, etc. Very interestingly, the scroll will be abandoned and the codex will generalize in China around that time, as observed by Ann Blair in her book /TOO MUCH TO KNOW/, Yale Univ. Press, 2010 (pp. 28-31).
 
Most of the leishus *were printed* (from the IXth century on!). The picture on the right side (a banknote printing plate) is there to remind us of who was (by far) the most advanced at that time. The Chinese were of course printing their leishus on paper that they discovered in the VIIIth century BCE.

** Getting organized by using the right slot

Now that we briefly reviewed the timeline of the main navigation elements of the books---navigation elements that can of course be applied to our lab/note-books---we come back to the paper slips and cards as notes media.

We see (again) Placcius' and Leibniz's closet since it displays both the benefits and the shortcomings of media that hold *a single note*.

Obvious shortcomings are:
- Paper slips and cards get easily lost.
- They are essentially useless if they are not *classified* in addition to being filed.
These problems are solved by Placcius' cabinet, the content of which is fundamentally accessed through the index.

Clear benefits are:
- Paper slips can be easily reorganized when they contain information on several subjects.
- Paper slips can be directly pasted in a book when composing an anthology or a compendium.

This last technique (pasting when making an anthology) was systematically used by the Renaissance polymath [[https://en.wikipedia.org/wiki/Conrad_Gessner][Conrad Gessner]] (1516-1565) who even got his paper slips by cutting parts of pages from books (don't do that with library books)!

** Constructing a notebook index the John Locke way

We will now learn about an index construction technique due to [[https://en.wikipedia.org/wiki/John_Locke][John Locke]] (1632-1704), the grand-father of liberalism and a major investor in the /Royal African Company/, the largest company in the [[https://en.wikipedia.org/wiki/John_Locke#Constitution_of_Carolina][slave-trade]] business at that time...

The indexing method is here illustrated using my own notebook. The two pages that are displayed describe the structure of a dataset in the [[https://www.hdfgroup.org/][HDF5]] format on the left side and the corresponding structure (designed to map the former one) of a =data frame= object of the [[https://www.r-project.org/][R]] language. This dataset contain *calcium* concentration measurements made in *neurons*. This notes were taken while writing some computer *code* to analyze the data.

The precise content of the pages does not matter here in order to understand how Locke's method works. The important points are:
- The pages are numbered (we are seeing here pages 86 and 87).
- Keywords are written at the bottom of the page: *code*; *neuro*; *calcium*.

This method can be applied after note-taking, you just need to have few pages left at the end of your notebook. That's in fact what I did since I had started filling my notebook before learning about the method (I learned about while preparing the French version of this lecture in September 2017).


We now the index. It is located at the end of the notebook although Locke recommends placing it at the beginning. Since I did not know about the method when I started the notebook, I had to place it at the end...

The idea is to enter the keywords used in the notebook based on their *first letter* and the *first vowel following the first letter*.

The index is therefore made of the 26 letters (you see letters "A" to "R" here, the remaining ones are on the next page) subdivided the five most common vowels ("y" goes together with "i" in that case).

Pages 86 and 87 contained the keyword *code* that goes into the entry "Co" of the index (you see "86-89" because the following pages also concern code for the same project). The keyword *Neuro* giving an entry on line "Ne", while the keyword *Calcium* gives an entry on line "Ca".

The keyword *Criquet* (not shown above) gives an entry on line "Ci".

It is also a good idea to list the set of keywords used in the notebook on the page preceding or following the index.
