#+TITLE: Joël Zaffran interview
#+Date: <déc 2019>
#+Author: Joël Zaffran
#+LANGUAGE: en

** Biography
   :PROPERTIES:
   :CUSTOM_ID: biography
   :END:

*Joël Zaffran* is a professor of sociology at the University of Bordeaux
and a researcher at the Centre Émile Durkheim, a laboratory whose
specificity is that it brings together researchers in political science
and sociology.

** Interview
   :PROPERTIES:
   :CUSTOM_ID: interview
   :END:

*** What is your field of research? What methods do you use in data processing?
    :PROPERTIES:
    :CUSTOM_ID: what-is-your-field-of-research-what-methods-do-you-use-in-data-processing
    :END:

My research fields are education and youth on one hand, and disabilities
on the other. From a methodological standpoint, I use both quantitative
and qualitative approaches. I often try to combine the two approaches in
order to look at the research object from different perspectives. I use
a number of different software programs in this context, sometimes
simultaneously.

*** What type of data do you work on (e.g. survey data, etc.) and what constraints are linked to these types of data (e.g. confidentiality)? How do you handle these constraints?
    :PROPERTIES:
    :CUSTOM_ID: what-type-of-data-do-you-work-on-e.g.survey-data-etc.-and-what-constraints-are-linked-to-these-types-of-data-e.g.confidentiality-how-do-you-handle-these-constraints
    :END:

The quantitative data I work on either comes from /ad-hoc/
questionnaires that I devise based on my hypotheses, before distributing
them using Sphinx; or from secondary analysis. In both cases, there is
an issue of confidentiality, together with the constraint from the CNIL.

On one hand, this implies prior authorisation from the CNIL subsequent
to a request being made on their site; on the other, individuals are
rendered anonymous while the results are being produced. Then there is
the fact that I use Sphinx, which enables me to store my data on the
university server. The advantage of this is that access to this data is
protected.

*** In your field, what major evolutions have there been in terms of data processing? This might be in terms of methods (e.g. new statistics) or tools (e.g. more widespread use of R, etc.)
    :PROPERTIES:
    :CUSTOM_ID: in-your-field-what-major-evolutions-have-there-been-in-terms-of-data-processing-this-might-be-in-terms-of-methods-e.g.new-statistics-or-tools-e.g.more-widespread-use-of-r-etc.
    :END:

For me, the major revolution has been the switch from SPSS to R. This
was a forced switch as a result of budgetary restrictions at the
university. I was teaching my students SPSS, and I had to switch to R
(which has the advantage of being freeware) in order to be able to
continue teaching. That said, I have an SPSS license on my personal
computer, meaning it is not uncommon for me to switch from Sphinx to
SPSS and from SPSS to R when using data from my surveys.

There are a number of advantages to this way of working. First and
foremost, R enables me to move from statistical analysis of quantitative
data to statistical analysis of lexical data (enabling me to do
iramuteq). I recently had to carry out a survival analysis on course
data. SPSS does not provide (to the best of my knowledge) either a
"hazard ratio" table or the graphs from the Schoenfeld test, but there
is an R script for that.

*** How do you handle the issue of transparency in your field of research? What are the critical aspects in your discipline? Not all of the data is going to be shared, but how do you deal with being able to retrace your research process? What practices have you adopted?
    :PROPERTIES:
    :CUSTOM_ID: how-do-you-handle-the-issue-of-transparency-in-your-field-of-research-what-are-the-critical-aspects-in-your-discipline-not-all-of-the-data-is-going-to-be-shared-but-how-do-you-deal-with-being-able-to-retrace-your-research-process-what-practices-have-you-adopted
    :END:

As I said, my field is the humanities, more specifically sociology. In
this field, the issue of transparency is not exactly the same as it is
in the hard sciences, where the challenges, both scientific and
academic, are different. *However, the issue of being able to retrace
the research process is the same, regardless of the discipline.* From my
perspective, this involves *keeping a record of the scripts and tables
built before publishing the results in the form of an article*.

This is no easy feat, since, as we all know, *articles do not accurately
reflect research processes ahead of publication*.

I have two ways of working: the first involves specifying the approach
and the method in a *methodological insert* included in the body of the
article. The second involves always *naming each table or script before
saving it*. This helps you get your bearings among the mass of files
created.

*** Which tools do you use? The use of proprietary software, for example (SAS, SPSS, etc.) raises a number of issues with regard to reproducible research because the source code is not available.
    :PROPERTIES:
    :CUSTOM_ID: which-tools-do-you-use-the-use-of-proprietary-software-for-example-sas-spss-etc.-raises-a-number-of-issues-with-regard-to-reproducible-research-because-the-source-code-is-not-available.
    :END:

In terms of traceability, *R is easier to use in that all of the scripts
used are recorded chronologically*, meaning all you need to do is to
give each one a title (making sure to include the symbol # first). This
is harder with SPSS. It was for this reason, as I was saying, that I
opted for SPSS for step by step recordings of lists of results.

*** Could you tell us about any horror stories you have had? i.e. a major problem (e.g. data not available; not being able to reproduce a figure and obtain the same result, not being able to supply a referee with data, etc.)
    :PROPERTIES:
    :CUSTOM_ID: could-you-tell-us-about-any-horror-stories-you-have-had-i.e.a-major-problem-e.g.data-not-available-not-being-able-to-reproduce-a-figure-and-obtain-the-same-result-not-being-able-to-supply-a-referee-with-data-etc.
    :END:

My biggest mistake happened when *reviewers asked me to redo a
regression model*. The problem was that I was *unable to find the
variables that had been recoded and was faced with the nightmare of
having to recode everything* and to redo all of the tables before I was
able to redo the analysis the way the reviewers were expecting. My
biggest disappointment came when I saw that the results that had
initially been presented were barely any different from the results
produced after having reworked the data the way the reviewers wanted me
to.
